# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  autosave-nvim = {
    pname = "autosave-nvim";
    version = "3d342d6fcebeede15b6511b13a38a522c6f33bf8";
    src = fetchFromGitHub ({
      owner = "Pocco81";
      repo = "AutoSave.nvim";
      rev = "3d342d6fcebeede15b6511b13a38a522c6f33bf8";
      fetchSubmodules = false;
      sha256 = "sha256-1tAYnd4/hGgG2NG8n9hZi9zWM+v1OTh0YBlG8kEZeXI=";
    });
  };
  circles-nvim = {
    pname = "circles-nvim";
    version = "3847feed23fa3ba6abecdf1b17a6c7d2022ebe65";
    src = fetchFromGitHub ({
      owner = "projekt0n";
      repo = "circles.nvim";
      rev = "3847feed23fa3ba6abecdf1b17a6c7d2022ebe65";
      fetchSubmodules = false;
      sha256 = "sha256-uSkIJD8tJVx2jzbMbN8mEg10sgdvtHgYdRyj5kKPrvM=";
    });
  };
  coq-3p = {
    pname = "coq-3p";
    version = "d3873bacc99c87a71ab68a93f279f598aad7b2f3";
    src = fetchFromGitHub ({
      owner = "ms-jpq";
      repo = "coq.thirdparty";
      rev = "d3873bacc99c87a71ab68a93f279f598aad7b2f3";
      fetchSubmodules = false;
      sha256 = "sha256-i6KbQ+MRw6/LommOr1BVHiIfiSxMF0e+1L2VmL2B2gM=";
    });
  };
  coq-artifacts = {
    pname = "coq-artifacts";
    version = "db944379f1b0e7f66274707ff5719d260a0b9128";
    src = fetchFromGitHub ({
      owner = "ms-jpq";
      repo = "coq.artifacts";
      rev = "db944379f1b0e7f66274707ff5719d260a0b9128";
      fetchSubmodules = false;
      sha256 = "sha256-BaFbzRPZDWZpYZvW+9r6LrKZbmwq5BxnSqO1N5SRoMI=";
    });
  };
  coq-nvim = {
    pname = "coq-nvim";
    version = "a8955f1c2b16b196472cd3f91b30b0ea2678e1fd";
    src = fetchFromGitHub ({
      owner = "ms-jpq";
      repo = "coq_nvim";
      rev = "a8955f1c2b16b196472cd3f91b30b0ea2678e1fd";
      fetchSubmodules = false;
      sha256 = "sha256-+52X16DHoRCuU8bHZ82F9+5wlqnZqUr7yUaa+/70zag=";
    });
  };
  filetype-nvim = {
    pname = "filetype-nvim";
    version = "4d2c0d4488a05f9b0d18a7e2004c0182e350bb45";
    src = fetchFromGitHub ({
      owner = "nathom";
      repo = "filetype.nvim";
      rev = "4d2c0d4488a05f9b0d18a7e2004c0182e350bb45";
      fetchSubmodules = false;
      sha256 = "sha256-dzrJ8ddUnj7zRNLWlSoknXtSB0LT9VUuYnHSsBJpgGQ=";
    });
  };
  flutter-tools-nvim = {
    pname = "flutter-tools-nvim";
    version = "9458303fcaa5cc35e0b1915edb8509886ed986d7";
    src = fetchFromGitHub ({
      owner = "akinsho";
      repo = "flutter-tools.nvim";
      rev = "9458303fcaa5cc35e0b1915edb8509886ed986d7";
      fetchSubmodules = false;
      sha256 = "sha256-iTvYeb/dC0hmv9DO3EYmQy1WQIoDjm05bQub+cxtJBo=";
    });
  };
  focus-nvim = {
    pname = "focus-nvim";
    version = "b5fbfb23b769061e88e02431931e905fe78b55a6";
    src = fetchFromGitHub ({
      owner = "beauwilliams";
      repo = "focus.nvim";
      rev = "b5fbfb23b769061e88e02431931e905fe78b55a6";
      fetchSubmodules = false;
      sha256 = "sha256-KsmPTNqZU92ElEgoAy/rmX2QCjPlapefrP6uM+1oPB8=";
    });
  };
  hachiko = {
    pname = "hachiko";
    version = "447ea7b15e883c4662ff16e79d025d804d8a1812";
    src = fetchFromGitHub ({
      owner = "water-sucks";
      repo = "hachiko";
      rev = "447ea7b15e883c4662ff16e79d025d804d8a1812";
      fetchSubmodules = false;
      sha256 = "sha256-1KK6fhOFsR4I0qjv0+5CTx16T0MJ7dc0QFabuU8RLzA=";
    });
  };
  highstr-nvim = {
    pname = "highstr-nvim";
    version = "25ab3f02f6174394d93ae21914de0e552c255bb8";
    src = fetchFromGitHub ({
      owner = "Pocco81";
      repo = "HighStr.nvim";
      rev = "25ab3f02f6174394d93ae21914de0e552c255bb8";
      fetchSubmodules = false;
      sha256 = "sha256-n5DwdItMjhw4z09C1F3b+U5abwYnaok6OGCRmNMxTLY=";
    });
  };
  iswap-nvim = {
    pname = "iswap-nvim";
    version = "d70a864cb86cb75a2e942077ac68134291955899";
    src = fetchFromGitHub ({
      owner = "mizlan";
      repo = "iswap.nvim";
      rev = "d70a864cb86cb75a2e942077ac68134291955899";
      fetchSubmodules = false;
      sha256 = "sha256-BmxkaRROy3FCwsKLY2rz0jPB8e1AUfOj5tegShCSnKA=";
    });
  };
  nui-nvim = {
    pname = "nui-nvim";
    version = "6f803e88093573f73d4ee6c0dfe0575df3f97a9f";
    src = fetchFromGitHub ({
      owner = "MunifTanjim";
      repo = "nui.nvim";
      rev = "6f803e88093573f73d4ee6c0dfe0575df3f97a9f";
      fetchSubmodules = false;
      sha256 = "sha256-Pcq7TPKAZB/TUIWD//NY+aK6QNHOqQO6WLdB/Ea7yhY=";
    });
  };
  nvim-mapper = {
    pname = "nvim-mapper";
    version = "e11e852bafa41a4a2c160fcd2d38779add423db9";
    src = fetchFromGitHub ({
      owner = "lazytanuki";
      repo = "nvim-mapper";
      rev = "e11e852bafa41a4a2c160fcd2d38779add423db9";
      fetchSubmodules = false;
      sha256 = "sha256-eQbKy+MXRwhMXHPLTfRMc9xs3ZVcu/uXM++f0sHE6Bc=";
    });
  };
  renamer-nvim = {
    pname = "renamer-nvim";
    version = "80d627372f90660f135862c8a7f8941b28ee5373";
    src = fetchFromGitHub ({
      owner = "filipdutescu";
      repo = "renamer.nvim";
      rev = "80d627372f90660f135862c8a7f8941b28ee5373";
      fetchSubmodules = false;
      sha256 = "sha256-1+bvH/osLP1LBUNV4EkcZoKvSkT0cNnwSyOSjhE4mgI=";
    });
  };
  searchbox-nvim = {
    pname = "searchbox-nvim";
    version = "0b06f4a8f0b81016fb8d74824b84d71c421384e0";
    src = fetchFromGitHub ({
      owner = "VonHeikemen";
      repo = "searchbox.nvim";
      rev = "0b06f4a8f0b81016fb8d74824b84d71c421384e0";
      fetchSubmodules = false;
      sha256 = "sha256-JK2jjdaCm3YjD2C0QfFwHdRemDxmDnQTI0wCs5h0iHo=";
    });
  };
  sidebar-nvim = {
    pname = "sidebar-nvim";
    version = "7d516d963593ffb692db31448c82891b2c29f479";
    src = fetchFromGitHub ({
      owner = "sidebar-nvim";
      repo = "sidebar.nvim";
      rev = "7d516d963593ffb692db31448c82891b2c29f479";
      fetchSubmodules = false;
      sha256 = "sha256-0xwxRrpksOhUTSDKLKwH1a9QfN5wdcs+c3eEd63qAm8=";
    });
  };
  tetris = {
    pname = "tetris";
    version = "d17c99fb527ada98ffb0212ffc87ccda6fd4f7d9";
    src = fetchFromGitHub ({
      owner = "alec-gibson";
      repo = "nvim-tetris";
      rev = "d17c99fb527ada98ffb0212ffc87ccda6fd4f7d9";
      fetchSubmodules = false;
      sha256 = "sha256-+69Fq5aMMzg9nV05rZxlLTFwQmDyN5/5HmuL2SGu9xQ=";
    });
  };
  tmux-nvim = {
    pname = "tmux-nvim";
    version = "2535a67a78da737207c918106cade1ba016d9f6a";
    src = fetchFromGitHub ({
      owner = "aserowy";
      repo = "tmux.nvim";
      rev = "2535a67a78da737207c918106cade1ba016d9f6a";
      fetchSubmodules = false;
      sha256 = "sha256-nuDC4IGUqkGgM9q76WiHbYGEbLTnD561ioHKd96Z0u8=";
    });
  };
  windline-nvim = {
    pname = "windline-nvim";
    version = "15d3a880dd832d502789c020e65a523bedcacc04";
    src = fetchFromGitHub ({
      owner = "windwp";
      repo = "windline.nvim";
      rev = "15d3a880dd832d502789c020e65a523bedcacc04";
      fetchSubmodules = false;
      sha256 = "sha256-rQmYMKRPFub1Fq7Df7OF90mN7xYLSeD1TP+ZJk4gQzM=";
    });
  };
  zen-mode-nvim = {
    pname = "zen-mode-nvim";
    version = "f1cc53d32b49cf962fb89a2eb0a31b85bb270f7c";
    src = fetchFromGitHub ({
      owner = "folke";
      repo = "zen-mode.nvim";
      rev = "f1cc53d32b49cf962fb89a2eb0a31b85bb270f7c";
      fetchSubmodules = false;
      sha256 = "sha256-t+X4ObITdnpvs5olundHES28dS2d/Eoz4snMHrzNs7s=";
    });
  };
}
