# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  tree-sitter-norg = {
    pname = "tree-sitter-norg";
    version = "17d61df817c1e0a9cdef8d915d4e4c556b7cf68c";
    src = fetchFromGitHub ({
      owner = "nvim-neorg";
      repo = "tree-sitter-norg";
      rev = "17d61df817c1e0a9cdef8d915d4e4c556b7cf68c";
      fetchSubmodules = false;
      sha256 = "sha256-kM1Y1TpeXgkWk/N81vmtVS8SGw+U/fkYJQ467+6sN5g=";
    });
  };
  tree-sitter-norg-meta = {
    pname = "tree-sitter-norg-meta";
    version = "4687b53e656b920cde6c0b9a7b9acf9a665cd838";
    src = fetchFromGitHub ({
      owner = "nvim-neorg";
      repo = "tree-sitter-norg-meta";
      rev = "4687b53e656b920cde6c0b9a7b9acf9a665cd838";
      fetchSubmodules = false;
      sha256 = "sha256-+NInywA8KOfAVnetuRW/9GJIqFWijrMr23dhZx4b6EQ=";
    });
  };
  tree-sitter-norg-table = {
    pname = "tree-sitter-norg-table";
    version = "f354ea343b8803948e6e1df36eb586e31c529900";
    src = fetchFromGitHub ({
      owner = "nvim-neorg";
      repo = "tree-sitter-norg-table";
      rev = "f354ea343b8803948e6e1df36eb586e31c529900";
      fetchSubmodules = false;
      sha256 = "sha256-xTH4LmqhtfyN9JGQdquJLQz1McZQItdEY5HpJxbuYC0=";
    });
  };
}
