# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  autosave-nvim = {
    pname = "autosave-nvim";
    version = "3d342d6fcebeede15b6511b13a38a522c6f33bf8";
    src = fetchFromGitHub ({
      owner = "Pocco81";
      repo = "AutoSave.nvim";
      rev = "3d342d6fcebeede15b6511b13a38a522c6f33bf8";
      fetchSubmodules = false;
      sha256 = "sha256-1tAYnd4/hGgG2NG8n9hZi9zWM+v1OTh0YBlG8kEZeXI=";
    });
  };
  circles-nvim = {
    pname = "circles-nvim";
    version = "3847feed23fa3ba6abecdf1b17a6c7d2022ebe65";
    src = fetchFromGitHub ({
      owner = "projekt0n";
      repo = "circles.nvim";
      rev = "3847feed23fa3ba6abecdf1b17a6c7d2022ebe65";
      fetchSubmodules = false;
      sha256 = "sha256-uSkIJD8tJVx2jzbMbN8mEg10sgdvtHgYdRyj5kKPrvM=";
    });
  };
  coq-3p = {
    pname = "coq-3p";
    version = "7b63bec1aa31dbe353bd8cd28d797ef8905b920d";
    src = fetchFromGitHub ({
      owner = "ms-jpq";
      repo = "coq.thirdparty";
      rev = "7b63bec1aa31dbe353bd8cd28d797ef8905b920d";
      fetchSubmodules = false;
      sha256 = "sha256-RuAd7KBwhY1H//hzQ9J7Vdz54aEqn+bMI/GjJhWTZcc=";
    });
  };
  coq-artifacts = {
    pname = "coq-artifacts";
    version = "d3cb135dce14cfd586026c8de8123608db1f2c6a";
    src = fetchFromGitHub ({
      owner = "ms-jpq";
      repo = "coq.artifacts";
      rev = "d3cb135dce14cfd586026c8de8123608db1f2c6a";
      fetchSubmodules = false;
      sha256 = "sha256-Y1Tu2vKg/i/b5fVmp4VguzNgCTSE3UrR5/59JmER2pg=";
    });
  };
  coq-nvim = {
    pname = "coq-nvim";
    version = "de375a9508aab7614ce181afacc2ce8f7535b003";
    src = fetchFromGitHub ({
      owner = "ms-jpq";
      repo = "coq_nvim";
      rev = "de375a9508aab7614ce181afacc2ce8f7535b003";
      fetchSubmodules = false;
      sha256 = "sha256-zeY5UO2eWNbl4Zbs7RdwHDsB2sxrBFPBZsogMSCJToc=";
    });
  };
  filetype-nvim = {
    pname = "filetype-nvim";
    version = "5a9837d51da6c7c0767767e1ac224e074587a001";
    src = fetchFromGitHub ({
      owner = "nathom";
      repo = "filetype.nvim";
      rev = "5a9837d51da6c7c0767767e1ac224e074587a001";
      fetchSubmodules = false;
      sha256 = "sha256-M5+ByFdSxjnvABGkJB4K0fADIVLl+hl6WOjqHTXzSRY=";
    });
  };
  flutter-tools-nvim = {
    pname = "flutter-tools-nvim";
    version = "9301eeb3f1b4ea15845ee72f778b6af7bad60321";
    src = fetchFromGitHub ({
      owner = "akinsho";
      repo = "flutter-tools.nvim";
      rev = "9301eeb3f1b4ea15845ee72f778b6af7bad60321";
      fetchSubmodules = false;
      sha256 = "sha256-ETuyjiqfNRke0UBjv9zyUkIqieFBYxVms9WoKyk7LjA=";
    });
  };
  focus-nvim = {
    pname = "focus-nvim";
    version = "86d036649ab8d00ac8fdca750533a541b892e4fb";
    src = fetchFromGitHub ({
      owner = "beauwilliams";
      repo = "focus.nvim";
      rev = "86d036649ab8d00ac8fdca750533a541b892e4fb";
      fetchSubmodules = false;
      sha256 = "sha256-PYuy7OF+ZhSyXWInRBtfH4nvECU22BqvNLn553kvzUI=";
    });
  };
  guihua-lua = {
    pname = "guihua-lua";
    version = "ab54e02d2ab54fa310a0e5268b5ead5c045f2fab";
    src = fetchFromGitHub ({
      owner = "ray-x";
      repo = "guihua.lua";
      rev = "ab54e02d2ab54fa310a0e5268b5ead5c045f2fab";
      fetchSubmodules = false;
      sha256 = "sha256-Ne2Up7kMC3K4osxFQlBDG2nLa1aIZNvRo7HEZuVQmDU=";
    });
  };
  hachiko = {
    pname = "hachiko";
    version = "4b20ccd415910ec2517f3a88ca225b258087480c";
    src = fetchFromGitHub ({
      owner = "water-sucks";
      repo = "hachiko";
      rev = "4b20ccd415910ec2517f3a88ca225b258087480c";
      fetchSubmodules = false;
      sha256 = "sha256-70xV7hPBX7kgec4fCi/RPdigr+CKkNwB/q6p/kb+IzE=";
    });
  };
  highstr-nvim = {
    pname = "highstr-nvim";
    version = "25ab3f02f6174394d93ae21914de0e552c255bb8";
    src = fetchFromGitHub ({
      owner = "Pocco81";
      repo = "HighStr.nvim";
      rev = "25ab3f02f6174394d93ae21914de0e552c255bb8";
      fetchSubmodules = false;
      sha256 = "sha256-n5DwdItMjhw4z09C1F3b+U5abwYnaok6OGCRmNMxTLY=";
    });
  };
  iswap-nvim = {
    pname = "iswap-nvim";
    version = "68b1f49408e8489a4d223dea31965dc395c038fb";
    src = fetchFromGitHub ({
      owner = "mizlan";
      repo = "iswap.nvim";
      rev = "68b1f49408e8489a4d223dea31965dc395c038fb";
      fetchSubmodules = false;
      sha256 = "sha256-pRZIW08SgDNVtBzEgSiMCToZA8DnyxSEEW4s13kE1A8=";
    });
  };
  lsp-format-nvim = {
    pname = "lsp-format-nvim";
    version = "210c4c58eb3e4f1d97482c3172c8272305d46624";
    src = fetchFromGitHub ({
      owner = "lukas-reineke";
      repo = "lsp-format.nvim";
      rev = "210c4c58eb3e4f1d97482c3172c8272305d46624";
      fetchSubmodules = false;
      sha256 = "sha256-i19110kKfjj69/GIt4M1yxLj91INaDctdox2q73ypV4=";
    });
  };
  lsp-signature-nvim = {
    pname = "lsp-signature-nvim";
    version = "2496aac5930e40340578fb36f8e8fd4ae6cbfe73";
    src = fetchFromGitHub ({
      owner = "ray-x";
      repo = "lsp_signature.nvim";
      rev = "2496aac5930e40340578fb36f8e8fd4ae6cbfe73";
      fetchSubmodules = false;
      sha256 = "sha256-NbdkcdFT3SvlVW7bbbI6FYPVh3mcKi0aQPV7N6b5fdw=";
    });
  };
  navigator-lua = {
    pname = "navigator-lua";
    version = "b249d1680af27af155913b6947f0c4a6ddafee7f";
    src = fetchFromGitHub ({
      owner = "ray-x";
      repo = "navigator.lua";
      rev = "b249d1680af27af155913b6947f0c4a6ddafee7f";
      fetchSubmodules = false;
      sha256 = "sha256-dWC0wKbr5SnHE9502Yg05nylggDxdpFA+KdWBmteFpw=";
    });
  };
  nui-nvim = {
    pname = "nui-nvim";
    version = "abdbfab89f307151db83b1a5147cd390ef27ff99";
    src = fetchFromGitHub ({
      owner = "MunifTanjim";
      repo = "nui.nvim";
      rev = "abdbfab89f307151db83b1a5147cd390ef27ff99";
      fetchSubmodules = false;
      sha256 = "sha256-rnCwZMUEJi9r047YMDB2XO9panACtbxJdhWerK3TiXw=";
    });
  };
  nvim-mapper = {
    pname = "nvim-mapper";
    version = "e11e852bafa41a4a2c160fcd2d38779add423db9";
    src = fetchFromGitHub ({
      owner = "lazytanuki";
      repo = "nvim-mapper";
      rev = "e11e852bafa41a4a2c160fcd2d38779add423db9";
      fetchSubmodules = false;
      sha256 = "sha256-eQbKy+MXRwhMXHPLTfRMc9xs3ZVcu/uXM++f0sHE6Bc=";
    });
  };
  renamer-nvim = {
    pname = "renamer-nvim";
    version = "4a4707992a79f481f4882bab9b3823ac6455c942";
    src = fetchFromGitHub ({
      owner = "filipdutescu";
      repo = "renamer.nvim";
      rev = "4a4707992a79f481f4882bab9b3823ac6455c942";
      fetchSubmodules = false;
      sha256 = "sha256-JV/e8m1x6eZLCJgscsdnpZHv6rDJKI8rhVk+Xtff6vE=";
    });
  };
  searchbox-nvim = {
    pname = "searchbox-nvim";
    version = "bbb1c08a36d19517633430079ab0c61293e18b91";
    src = fetchFromGitHub ({
      owner = "VonHeikemen";
      repo = "searchbox.nvim";
      rev = "bbb1c08a36d19517633430079ab0c61293e18b91";
      fetchSubmodules = false;
      sha256 = "sha256-vxcqh2ExTUsye19c2jXoPMrbuYojzyz9Dq7UIrxhAdM=";
    });
  };
  sidebar-nvim = {
    pname = "sidebar-nvim";
    version = "90123bf8d4255016f06ef0a5de0617da77b83fc8";
    src = fetchFromGitHub ({
      owner = "sidebar-nvim";
      repo = "sidebar.nvim";
      rev = "90123bf8d4255016f06ef0a5de0617da77b83fc8";
      fetchSubmodules = false;
      sha256 = "sha256-FiFIE3kqk/usJeBDcXaHrovqXq68TMNauLl4PPO2zzc=";
    });
  };
  tetris = {
    pname = "tetris";
    version = "d17c99fb527ada98ffb0212ffc87ccda6fd4f7d9";
    src = fetchFromGitHub ({
      owner = "alec-gibson";
      repo = "nvim-tetris";
      rev = "d17c99fb527ada98ffb0212ffc87ccda6fd4f7d9";
      fetchSubmodules = false;
      sha256 = "sha256-+69Fq5aMMzg9nV05rZxlLTFwQmDyN5/5HmuL2SGu9xQ=";
    });
  };
  tmux-nvim = {
    pname = "tmux-nvim";
    version = "94a5b180b20b8374094f1170b26280898b4ca4d7";
    src = fetchFromGitHub ({
      owner = "aserowy";
      repo = "tmux.nvim";
      rev = "94a5b180b20b8374094f1170b26280898b4ca4d7";
      fetchSubmodules = false;
      sha256 = "sha256-2TV/SiIqcPzwq6f/Odn2JKaH0cGiNQ8ABqMSb4bXPw8=";
    });
  };
  windline-nvim = {
    pname = "windline-nvim";
    version = "b451bc8af3208657068ba20ec268cdfabbbbe3bc";
    src = fetchFromGitHub ({
      owner = "windwp";
      repo = "windline.nvim";
      rev = "b451bc8af3208657068ba20ec268cdfabbbbe3bc";
      fetchSubmodules = false;
      sha256 = "sha256-ROsyA8lCmZsqIn81L+VT4r3Rt1iXtf2sB5YZv8I03W8=";
    });
  };
  zen-mode-nvim = {
    pname = "zen-mode-nvim";
    version = "f1cc53d32b49cf962fb89a2eb0a31b85bb270f7c";
    src = fetchFromGitHub ({
      owner = "folke";
      repo = "zen-mode.nvim";
      rev = "f1cc53d32b49cf962fb89a2eb0a31b85bb270f7c";
      fetchSubmodules = false;
      sha256 = "sha256-t+X4ObITdnpvs5olundHES28dS2d/Eoz4snMHrzNs7s=";
    });
  };
}
