# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
}: {
  i2p-profile = {
    pname = "i2p-profile";
    version = "50b00c6c885572399b81047294d54627a1858020";
    src = fetchFromGitHub {
      owner = "i2p";
      repo = "i2p.firefox";
      rev = "50b00c6c885572399b81047294d54627a1858020";
      fetchSubmodules = false;
      sha256 = "sha256-FXfORFqrHKC+gQ8QNcy5kksoBFrLktuaBSJ3+bO1qCI=";
    };
  };
  simplefox-theme = {
    pname = "simplefox-theme";
    version = "a4c1ec7d2af121047f09da4a572960e032ca29a6";
    src = fetchFromGitHub {
      owner = "migueravila";
      repo = "SimpleFox";
      rev = "a4c1ec7d2af121047f09da4a572960e032ca29a6";
      fetchSubmodules = false;
      sha256 = "sha256-iNILXnOZYbzy2/HcUpyiq6VOLA2C6fogAAwSWsTun1U=";
    };
  };
}
