# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  arcadia-theme = {
    pname = "arcadia-theme";
    version = "d513fd79a460bf0360e95e16f7b0d19d3b06055d";
    src = fetchFromGitHub {
      owner = "tyrohellion";
      repo = "arcadia";
      rev = "d513fd79a460bf0360e95e16f7b0d19d3b06055d";
      fetchSubmodules = false;
      sha256 = "sha256-ced+nKCXch3QljaP7aZXQX/EgUTEs/MtCVCaTK8y4Bg=";
    };
    date = "2025-04-29";
  };
}
