# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  cascadefox-theme = {
    pname = "cascadefox-theme";
    version = "8700d7718d130023815f0b036f3b1c4aaa2d5392";
    src = fetchFromGitHub {
      owner = "cascadefox";
      repo = "cascade";
      rev = "8700d7718d130023815f0b036f3b1c4aaa2d5392";
      fetchSubmodules = false;
      sha256 = "sha256-uGC+SIRisABvulJcpiHwE4mhhwzMVtpo3RMJEJoCaPU=";
    };
    date = "2025-10-02";
  };
}
