# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  arcadia-theme = {
    pname = "arcadia-theme";
    version = "4f5b28ca133ae5dc1d52e7746fbabf014491ebdf";
    src = fetchFromGitHub {
      owner = "tyrohellion";
      repo = "arcadia";
      rev = "4f5b28ca133ae5dc1d52e7746fbabf014491ebdf";
      fetchSubmodules = false;
      sha256 = "sha256-glZ7GS2K2jyAf7Fir+taZzAe6OznHEewuj3clamUBTg=";
    };
    date = "2025-08-11";
  };
}
