keys:
  - &varun 522e3a7813b5d0b5d70e5a40a1f17e43f6747fc0
  - &SebastianJanikowski age12yl7t27k2hvdv0kt8ky2gmshfdt3ysw83zzjnk7fxxenqf3sv4zsjug5me
creation_rules:
  - path_regex: hosts/nixos/machines/SebastianJanikowski/secrets/[^/]+\.yml$
    key_groups:
      - pgp:
          - *varun
        age:
          - *SebastianJanikowski
