min_score = 3
default_scope = "CharlesWoodson"

[scopes.CharlesWoodson]
description = "NixOS flake configuration for CharlesWoodson"
options-list-file = "/run/current-system/etc/nixos-cli/options-cache.json"
options-list-cmd = '''
nix eval .#nixosConfigurations.CharlesWoodson --json --apply 'input: let
  inherit (input) options pkgs;

  optionsList = builtins.filter
    (v: v.visible && !v.internal)
    (pkgs.lib.optionAttrSetToDocList options);
in
  optionsList'
'''
evaluator = "nix eval .#nixosConfigurations.CharlesWoodson.config.{{ .Option }}"

[scopes.SebastianJanikowski]
description = "NixOS flake configuration for SebastianJanikowski"
options-list-file = "/run/current-system/etc/nixos-cli/options-cache.json"
options-list-cmd = '''
nix eval .#nixosConfigurations.SebastianJanikowski --json --apply 'input: let
  inherit (input) options pkgs;

  optionsList = builtins.filter
    (v: v.visible && !v.internal)
    (pkgs.lib.optionAttrSetToDocList options);
in
  optionsList'
'''
evaluator = "nix eval .#nixosConfigurations.SebastianJanikowski.config.{{ .Option }}"

[scopes.TimBrown]
description = "nix-darwin flake configuration for TimBrown"
options-list-cmd = '''
nix eval .#darwinConfigurations.TimBrown --json --apply 'input: let
  inherit (input) options pkgs;

  optionsList = builtins.filter
    (v: v.visible && !v.internal)
    (pkgs.lib.optionAttrSetToDocList options);
in
  optionsList'
'''
evaluator = "nix eval .#darwinConfigurations.TimBrown.config.{{ .Option }}"

[scopes.nixed-fp]
description = "flake-parts config for NixOS configuration"
options-list-cmd = "nix eval --json .#options-doc"
evaluator = "nix eval .#debug.config.{{ .Option }}"
