[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.lua]
command = "stylua"
options = ["-f", "./home/profiles/base/nvim/.stylua.toml"]
includes = ["*.lua"]

[formatter.haskell]
command = "fourmolu"
options = ["-m", "inplace"]
includes = ["*.hs"]

[formatter.prettier]
command = "prettier"
options = ["-w"]
includes = ["*.md", "*.css"]

[formatter.shell]
command = "shfmt"
options = ["-s"]
includes = ["*.sh"]
