[manix]
src.git = "https://github.com/mlvzk/manix"
fetch.github = "mlvzk/manix"

[picom]
src.git = "https://github.com/ibhagwan/picom"
fetch.github = "ibhagwan/picom"

[simplefox-theme]
src.git = "https://github.com/migueravila/SimpleFox"
fetch.github = "migueravila/SimpleFox"
