[manix]
src.git = "https://github.com/mlvzk/manix"
fetch.github = "mlvzk/manix"

[picom]
src.git = "https://github.com/ibhagwan/picom"
fetch.github = "ibhagwan/picom"

[simplefox-theme]
src.git = "https://github.com/migueravila/SimpleFox"
fetch.github = "migueravila/SimpleFox"

[filen-desktop]
src.github = "FilenCloudDienste/filen-desktop"
fetch.url = "https://github.com/FilenCloudDienste/filen-desktop/releases/download/$ver/filen-setup.AppImage"

[tidal-hifi]
src.github = "Mastermindzh/tidal-hifi"
fetch.url = "https://github.com/Mastermindzh/tidal-hifi/releases/download/$ver/tidal-hifi-$ver.AppImage"
