[manix]
src.git = "https://github.com/mlvzk/manix"
fetch.github = "mlvzk/manix"

[lightdm-slick-greeter]
src.github = "linuxmint/slick-greeter"
fetch.github = "linuxmint/slick-greeter"

[picom]
src.git = "https://github.com/ibhagwan/picom"
fetch.github = "ibhagwan/picom"

[filen-desktop]
src.github = "FilenCloudDienste/filen-desktop"
fetch.url = "https://github.com/FilenCloudDienste/filen-desktop/releases/download/$ver/filen-setup.AppImage"

[tidal-hifi]
src.github = "Mastermindzh/tidal-hifi"
fetch.url = "https://github.com/Mastermindzh/tidal-hifi/releases/download/$ver/tidal-hifi-$ver.AppImage"

[rescrobbled]
src.github = "InputUsername/rescrobbled"
fetch.github = "InputUsername/rescrobbled"
cargo_locks = [ "./Cargo.lock" ]
