[picom]
src.git = "https://github.com/ibhagwan/picom"
fetch.github = "ibhagwan/picom"

[filen-desktop]
# src.github = "FilenCloudDienste/filen-desktop"
src.manual = "2.0.3" # Pinning source for now, because it's not provided on the CDN
fetch.url = "https://cdn.filen.io/desktop/release/$ver/filen_x86_64.AppImage"

[rescrobbled]
src.github = "InputUsername/rescrobbled"
fetch.github = "InputUsername/rescrobbled"
cargo_locks = [ "./Cargo.lock" ]
