[manix]
src.git = "https://github.com/mlvzk/manix"
fetch.github = "mlvzk/manix"

[picom]
src.github_tag = "jonaburg/picom"
fetch.github = "jonaburg/picom"

[simplefox-theme]
src.git = "https://github.com/migueravila/SimpleFox"
fetch.github = "migueravila/SimpleFox"
