print(cyan() .. [[    __    __]])
print(cyan() .. [[   /_/ /\ \_\]])
print(cyan() .. [[  __ \ \/ / __]])
print(cyan() .. [[  \_\_\/\/_/_/]])
print(cyan() .. [[/\___\_\/_/___/\]])
print(cyan() .. [[\/ __/_/\_\__ \/]])
print(cyan() .. [[  /_/ /\/\ \_\]])
print(cyan() .. [[   __/ /\ \__]])
print(cyan() .. [[   \_\ \/ /_/]])
print(reset())
