[fast-syntax-highlighting]
src.github_tag = "zdharma-continuum/fast-syntax-highlighting"
fetch.github = "zdharma-continuum/fast-syntax-highlighting"

[nix-shell]
src.github = "chisui/zsh-nix-shell"
fetch.github = "chisui/zsh-nix-shell"

[zsh-autosuggestions]
src.github_tag = "zsh-users/zsh-autosuggestions"
fetch.github = "zsh-users/zsh-autosuggestions"
