# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  cascade-theme = {
    pname = "cascade-theme";
    version = "a89173a67696a8bf43e8e2ac7ed93ba7903d7a70";
    src = fetchFromGitHub {
      owner = "andreasgrafen";
      repo = "cascade";
      rev = "a89173a67696a8bf43e8e2ac7ed93ba7903d7a70";
      fetchSubmodules = false;
      sha256 = "sha256-D4ZZPm/li1Eoo1TmDS/lI2MAlgosNGOOk4qODqIaCes=";
    };
    date = "2023-04-10";
  };
}
