# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  cascade-theme = {
    pname = "cascade-theme";
    version = "e5d9d9b81eb9ea16e27e72087ca6a39cf17594bd";
    src = fetchFromGitHub {
      owner = "andreasgrafen";
      repo = "cascade";
      rev = "e5d9d9b81eb9ea16e27e72087ca6a39cf17594bd";
      fetchSubmodules = false;
      sha256 = "sha256-xOihSEXn73tNSv1GhJJzBHXg+8azLvR3H/Iu+vM0y3w=";
    };
    date = "2023-12-19";
  };
}
