# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
}: {
  "'plugin-Comment.nvim'" = {
    pname = "'plugin-Comment.nvim'";
    version = "5f01c1a89adafc52bf34e3bf690f80d9d726715d";
    src = fetchFromGitHub {
      owner = "numToStr";
      repo = "Comment.nvim";
      rev = "5f01c1a89adafc52bf34e3bf690f80d9d726715d";
      fetchSubmodules = false;
      sha256 = "sha256-po1MyuuOH3e8yJTAtkxnusFSJuNpQnjpe+zfWPoO62E=";
    };
  };
  "'plugin-HighStr.nvim'" = {
    pname = "'plugin-HighStr.nvim'";
    version = "1cb5e030bb16df52c8428b53dc235466a4eb1d01";
    src = fetchFromGitHub {
      owner = "Pocco81";
      repo = "HighStr.nvim";
      rev = "1cb5e030bb16df52c8428b53dc235466a4eb1d01";
      fetchSubmodules = false;
      sha256 = "sha256-oyCCYgFckG3F9OKOeajLrLsby2Z+4zJ1RtwEzJo9JIk=";
    };
  };
  "'plugin-aerial.nvim'" = {
    pname = "'plugin-aerial.nvim'";
    version = "4b42ddbd453caec3b12541af80e498a02d47cf20";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "aerial.nvim";
      rev = "4b42ddbd453caec3b12541af80e498a02d47cf20";
      fetchSubmodules = false;
      sha256 = "sha256-50FhlrTALe4kgC5Z8fkMbllKTThk5/uok3X/WQutnYU=";
    };
  };
  "'plugin-auto-save.nvim'" = {
    pname = "'plugin-auto-save.nvim'";
    version = "979b6c82f60cfa80f4cf437d77446d0ded0addf0";
    src = fetchFromGitHub {
      owner = "Pocco81";
      repo = "auto-save.nvim";
      rev = "979b6c82f60cfa80f4cf437d77446d0ded0addf0";
      fetchSubmodules = false;
      sha256 = "sha256-bWGil73YiCKZEaY7IuUOIU4Q7k7qCMjSeQ4I+cAVe44=";
    };
  };
  "'plugin-bufferline.nvim'" = {
    pname = "'plugin-bufferline.nvim'";
    version = "4ecfa81e470a589e74adcde3d5bb1727dd407363";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "bufferline.nvim";
      rev = "4ecfa81e470a589e74adcde3d5bb1727dd407363";
      fetchSubmodules = false;
      sha256 = "sha256-qGl1jwBaMFWsrth7F20KrfJpyVENF8GEOJsVBBcSTVA=";
    };
  };
  "'plugin-circles.nvim'" = {
    pname = "'plugin-circles.nvim'";
    version = "67bc0cb720ed2f6d57073b24a7c1cf0531f2ce7e";
    src = fetchFromGitHub {
      owner = "projekt0n";
      repo = "circles.nvim";
      rev = "67bc0cb720ed2f6d57073b24a7c1cf0531f2ce7e";
      fetchSubmodules = false;
      sha256 = "sha256-6/J1FsCm2/kTzhmiVVxtLve4vbi0teVEPbUSq7X0CGE=";
    };
  };
  "'plugin-coq.artifacts'" = {
    pname = "'plugin-coq.artifacts'";
    version = "3ba5d159c41915cb882781bd06f26f351338e54c";
    src = fetchFromGitHub {
      owner = "ms-jpq";
      repo = "coq.artifacts";
      rev = "3ba5d159c41915cb882781bd06f26f351338e54c";
      fetchSubmodules = false;
      sha256 = "sha256-yUAkdPdaMyA3fWZP9yjNHv/6SacLemgKSuiOf46Rc04=";
    };
  };
  "'plugin-coq.thirdparty'" = {
    pname = "'plugin-coq.thirdparty'";
    version = "a6a52bc30497222e95f81b99df5bc4b999f75ba0";
    src = fetchFromGitHub {
      owner = "ms-jpq";
      repo = "coq.thirdparty";
      rev = "a6a52bc30497222e95f81b99df5bc4b999f75ba0";
      fetchSubmodules = false;
      sha256 = "sha256-QrpJ3ap9ADPOEJuRQJ9dH/cWob3GaOz6UseucTH1nWs=";
    };
  };
  "'plugin-coq_nvim'" = {
    pname = "'plugin-coq_nvim'";
    version = "07d1b5582e0b327becc9bfad7979699caf1da68a";
    src = fetchFromGitHub {
      owner = "ms-jpq";
      repo = "coq_nvim";
      rev = "07d1b5582e0b327becc9bfad7979699caf1da68a";
      fetchSubmodules = false;
      sha256 = "sha256-zIYsjULG3e38NTghAu8w1ek1ddtoaCwHKlyWPGtrMYE=";
    };
  };
  "'plugin-dial.nvim'" = {
    pname = "'plugin-dial.nvim'";
    version = "9ba17c2ee636a8e7fdef5b69d6aac54dd26f4384";
    src = fetchFromGitHub {
      owner = "monaqa";
      repo = "dial.nvim";
      rev = "9ba17c2ee636a8e7fdef5b69d6aac54dd26f4384";
      fetchSubmodules = false;
      sha256 = "sha256-OPWB8COt5Dri1GDLGi5jmYr71AbS+trfRPsxXdFrQjA=";
    };
  };
  "'plugin-diffview.nvim'" = {
    pname = "'plugin-diffview.nvim'";
    version = "f32a7224096cca11c3c91b0dd412808e63f3d720";
    src = fetchFromGitHub {
      owner = "sindrets";
      repo = "diffview.nvim";
      rev = "f32a7224096cca11c3c91b0dd412808e63f3d720";
      fetchSubmodules = false;
      sha256 = "sha256-aDweuvwkF8kb+lFUuBxgPeNfhX9wnm93LcBea7HkrSg=";
    };
  };
  "'plugin-dressing.nvim'" = {
    pname = "'plugin-dressing.nvim'";
    version = "7894d5bc504deacf37f0a479a53fa4746fe30a45";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "dressing.nvim";
      rev = "7894d5bc504deacf37f0a479a53fa4746fe30a45";
      fetchSubmodules = false;
      sha256 = "sha256-gR+cvJztRhkQ+vGhZ1JYgyEZA2TjNaJ1aGkeTA3yiMs=";
    };
  };
  "'plugin-editorconfig.nvim'" = {
    pname = "'plugin-editorconfig.nvim'";
    version = "2af880947129f1ab776b732a4eecb92528472ef5";
    src = fetchFromGitHub {
      owner = "gpanders";
      repo = "editorconfig.nvim";
      rev = "2af880947129f1ab776b732a4eecb92528472ef5";
      fetchSubmodules = false;
      sha256 = "sha256-PM6GEUJMJTFD5AAS+hZy+l//tCPLeezxIcAZiooBZ+c=";
    };
  };
  "'plugin-filetype.nvim'" = {
    pname = "'plugin-filetype.nvim'";
    version = "b522628a45a17d58fc0073ffd64f9dc9530a8027";
    src = fetchFromGitHub {
      owner = "nathom";
      repo = "filetype.nvim";
      rev = "b522628a45a17d58fc0073ffd64f9dc9530a8027";
      fetchSubmodules = false;
      sha256 = "sha256-B+VvgQj8akiKe+MX/dV2/mdaaqF8s2INW3phdPJ5TFA=";
    };
  };
  "'plugin-flutter-tools.nvim'" = {
    pname = "'plugin-flutter-tools.nvim'";
    version = "b666a057108c7655882cbc64217222228aad68da";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "flutter-tools.nvim";
      rev = "b666a057108c7655882cbc64217222228aad68da";
      fetchSubmodules = false;
      sha256 = "sha256-/9+6znJ5YA/yTNp5nZlusG5+FF4Ogz0QluuPbdmtX1Q=";
    };
  };
  "'plugin-github-nvim-theme'" = {
    pname = "'plugin-github-nvim-theme'";
    version = "a0632f9fa9b696896d4b427de0c84c1e9f192204";
    src = fetchFromGitHub {
      owner = "projekt0n";
      repo = "github-nvim-theme";
      rev = "a0632f9fa9b696896d4b427de0c84c1e9f192204";
      fetchSubmodules = false;
      sha256 = "sha256-cd9a8s2WIijsi4nvP1iu7/Dz7Mq8fxwFT0qOPuvyy00=";
    };
  };
  "'plugin-gitsigns.nvim'" = {
    pname = "'plugin-gitsigns.nvim'";
    version = "9ff7dfb051e5104088ff80556203634fc8f8546d";
    src = fetchFromGitHub {
      owner = "lewis6991";
      repo = "gitsigns.nvim";
      rev = "9ff7dfb051e5104088ff80556203634fc8f8546d";
      fetchSubmodules = false;
      sha256 = "sha256-u8nHB4QwP1hkfI64MGF5luTof88hTdpF5s1KBr3X2jE=";
    };
  };
  "'plugin-impatient.nvim'" = {
    pname = "'plugin-impatient.nvim'";
    version = "d3dd30ff0b811756e735eb9020609fa315bfbbcc";
    src = fetchFromGitHub {
      owner = "lewis6991";
      repo = "impatient.nvim";
      rev = "d3dd30ff0b811756e735eb9020609fa315bfbbcc";
      fetchSubmodules = false;
      sha256 = "sha256-tsdTHbUC0kYOGonJ1TLIsHnv/RgWGTqHKY3xVj80mxM=";
    };
  };
  "'plugin-indent-blankline.nvim'" = {
    pname = "'plugin-indent-blankline.nvim'";
    version = "db7cbcb40cc00fc5d6074d7569fb37197705e7f6";
    src = fetchFromGitHub {
      owner = "lukas-reineke";
      repo = "indent-blankline.nvim";
      rev = "db7cbcb40cc00fc5d6074d7569fb37197705e7f6";
      fetchSubmodules = false;
      sha256 = "sha256-d+G+tLdvD8OxENIRobAv0ATl4gGQdoz3RPuBrPA3PuU=";
    };
  };
  "'plugin-leap.nvim'" = {
    pname = "'plugin-leap.nvim'";
    version = "cd90202232806ec2dab9c76c7287bd2190a17459";
    src = fetchFromGitHub {
      owner = "ggandor";
      repo = "leap.nvim";
      rev = "cd90202232806ec2dab9c76c7287bd2190a17459";
      fetchSubmodules = false;
      sha256 = "sha256-Svubm4wZ4DmXnRNKuUJJLk1LWsXQvYIUafRoSJpBZjo=";
    };
  };
  "'plugin-lsp-format.nvim'" = {
    pname = "'plugin-lsp-format.nvim'";
    version = "b611bd6cea82ccc127cf8fd781a1cb784b0d6d3c";
    src = fetchFromGitHub {
      owner = "lukas-reineke";
      repo = "lsp-format.nvim";
      rev = "b611bd6cea82ccc127cf8fd781a1cb784b0d6d3c";
      fetchSubmodules = false;
      sha256 = "sha256-oa5gRKDSzsnk8+1t1eaAUX8OOjyWV7sssSl2xApNoOs=";
    };
  };
  "'plugin-lsp_signature.nvim'" = {
    pname = "'plugin-lsp_signature.nvim'";
    version = "12c0807919ae60c7bdae8c0bd0072ee9d752fa1a";
    src = fetchFromGitHub {
      owner = "ray-x";
      repo = "lsp_signature.nvim";
      rev = "12c0807919ae60c7bdae8c0bd0072ee9d752fa1a";
      fetchSubmodules = false;
      sha256 = "sha256-ab5XtGUQv4UpotzxCuqPGOQkd4MT8gKL7unhT8GCwwM=";
    };
  };
  "'plugin-ltex_extra.nvim'" = {
    pname = "'plugin-ltex_extra.nvim'";
    version = "a92e7baa6eb0352a52af3e0873f5cab9f07bf6b4";
    src = fetchFromGitHub {
      owner = "barreiroleo";
      repo = "ltex_extra.nvim";
      rev = "a92e7baa6eb0352a52af3e0873f5cab9f07bf6b4";
      fetchSubmodules = false;
      sha256 = "sha256-fTeO0oqVso6izmc6nWGoipykfNw9o4J2Xl3KUmkybj0=";
    };
  };
  "'plugin-lualine.nvim'" = {
    pname = "'plugin-lualine.nvim'";
    version = "3325d5d43a7a2bc9baeef2b7e58e1d915278beaf";
    src = fetchFromGitHub {
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "3325d5d43a7a2bc9baeef2b7e58e1d915278beaf";
      fetchSubmodules = false;
      sha256 = "sha256-pjpxV59Ej7tCvReP5nFi/h1veGwzLdw3PILC89+f488=";
    };
  };
  "'plugin-neodev.nvim'" = {
    pname = "'plugin-neodev.nvim'";
    version = "071c8895bbff0e4d1d3d4c531adfe20e3a2a6e82";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "neodev.nvim";
      rev = "071c8895bbff0e4d1d3d4c531adfe20e3a2a6e82";
      fetchSubmodules = false;
      sha256 = "sha256-CQNLCwSYLpRgmYDBlsJVPYnitocaEsWE1qKEagblIGI=";
    };
  };
  "'plugin-neorg'" = {
    pname = "'plugin-neorg'";
    version = "5a77759f763e5170b3cb0bb04a3ece0e051fcaf4";
    src = fetchFromGitHub {
      owner = "nvim-neorg";
      repo = "neorg";
      rev = "5a77759f763e5170b3cb0bb04a3ece0e051fcaf4";
      fetchSubmodules = false;
      sha256 = "sha256-WTRpjkWya/h6FEzcdBPNzD9iJ8ocPkQyuf9kFKGwFGU=";
    };
  };
  "'plugin-neorg-telescope'" = {
    pname = "'plugin-neorg-telescope'";
    version = "8d15129818c5dc224be97c9c6350d3386addeac8";
    src = fetchFromGitHub {
      owner = "nvim-neorg";
      repo = "neorg-telescope";
      rev = "8d15129818c5dc224be97c9c6350d3386addeac8";
      fetchSubmodules = false;
      sha256 = "sha256-KDEziW99VyW2RjGV0+JaLSXXZ66WSNVPBNaw6N7Fri0=";
    };
  };
  "'plugin-null-ls.nvim'" = {
    pname = "'plugin-null-ls.nvim'";
    version = "07d4ed4c6b561914aafd787453a685598bec510f";
    src = fetchFromGitHub {
      owner = "jose-elias-alvarez";
      repo = "null-ls.nvim";
      rev = "07d4ed4c6b561914aafd787453a685598bec510f";
      fetchSubmodules = false;
      sha256 = "sha256-yo43otYojyGRRNqpYotdheNNbcnSreNEdqZ5irTnbqs=";
    };
  };
  "'plugin-nvim-autopairs'" = {
    pname = "'plugin-nvim-autopairs'";
    version = "6b6e35fc9aca1030a74cc022220bc22ea6c5daf4";
    src = fetchFromGitHub {
      owner = "windwp";
      repo = "nvim-autopairs";
      rev = "6b6e35fc9aca1030a74cc022220bc22ea6c5daf4";
      fetchSubmodules = false;
      sha256 = "sha256-O9QRLKr6I2csBxKE6fyvkcA7Vgs7PjaQSC4bB7yaWtE=";
    };
  };
  "'plugin-nvim-code-action-menu'" = {
    pname = "'plugin-nvim-code-action-menu'";
    version = "58e12501ea028ff1171f8f06ea53891f7c6e1c3f";
    src = fetchFromGitHub {
      owner = "weilbith";
      repo = "nvim-code-action-menu";
      rev = "58e12501ea028ff1171f8f06ea53891f7c6e1c3f";
      fetchSubmodules = false;
      sha256 = "sha256-QvSP4ADZV0bCJTv3lwUNcVN/wr5XZ04d1/KIzKfLbqM=";
    };
  };
  "'plugin-nvim-colorizer.lua'" = {
    pname = "'plugin-nvim-colorizer.lua'";
    version = "36c610a9717cc9ec426a07c8e6bf3b3abcb139d6";
    src = fetchFromGitHub {
      owner = "norcalli";
      repo = "nvim-colorizer.lua";
      rev = "36c610a9717cc9ec426a07c8e6bf3b3abcb139d6";
      fetchSubmodules = false;
      sha256 = "sha256-6YrnItxExL2C8pNIdLd+hXCjsB2MbZANwWkah6dreD8=";
    };
  };
  "'plugin-nvim-dap'" = {
    pname = "'plugin-nvim-dap'";
    version = "61643680dcb771a29073cd432894e2f81a7c2ae3";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-dap";
      rev = "61643680dcb771a29073cd432894e2f81a7c2ae3";
      fetchSubmodules = false;
      sha256 = "sha256-9TcJNtZyde8DmKYb87q/4BTTAJVyGEO+ZxwE83Q2jmE=";
    };
  };
  "'plugin-nvim-dap-go'" = {
    pname = "'plugin-nvim-dap-go'";
    version = "c75921726ccfe97070285f206de49eddff276ea5";
    src = fetchFromGitHub {
      owner = "leoluz";
      repo = "nvim-dap-go";
      rev = "c75921726ccfe97070285f206de49eddff276ea5";
      fetchSubmodules = false;
      sha256 = "sha256-utDon+npwT1wT+clL+y+pau515hCUdeqvfUDPucu/+k=";
    };
  };
  "'plugin-nvim-dap-python'" = {
    pname = "'plugin-nvim-dap-python'";
    version = "27a0eff2bd3114269bb010d895b179e667e712bd";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-dap-python";
      rev = "27a0eff2bd3114269bb010d895b179e667e712bd";
      fetchSubmodules = false;
      sha256 = "sha256-UlwLESRrfwtzQGP30nYVkELAQWs85eyo9ORIjMLr198=";
    };
  };
  "'plugin-nvim-dap-ui'" = {
    pname = "'plugin-nvim-dap-ui'";
    version = "aec0163784ac3c6d25c3735fbabdd5b294f21670";
    src = fetchFromGitHub {
      owner = "rcarriga";
      repo = "nvim-dap-ui";
      rev = "aec0163784ac3c6d25c3735fbabdd5b294f21670";
      fetchSubmodules = false;
      sha256 = "sha256-L7fBJMlmTI90jZBH2b/TOQuhuuxyR+QTlBTswDZjxMU=";
    };
  };
  "'plugin-nvim-dap-virtual-text'" = {
    pname = "'plugin-nvim-dap-virtual-text'";
    version = "2971ce3e89b1711cc26e27f73d3f854b559a77d4";
    src = fetchFromGitHub {
      owner = "theHamsta";
      repo = "nvim-dap-virtual-text";
      rev = "2971ce3e89b1711cc26e27f73d3f854b559a77d4";
      fetchSubmodules = false;
      sha256 = "sha256-6QRDR0Oi2lQJGD2yiHr+NeVUeW0jAWY0Cj0gQ1dlBkM=";
    };
  };
  "'plugin-nvim-gomove'" = {
    pname = "'plugin-nvim-gomove'";
    version = "2b44ae7ac0804f4e3959228122f7c85bef1964e3";
    src = fetchFromGitHub {
      owner = "booperlv";
      repo = "nvim-gomove";
      rev = "2b44ae7ac0804f4e3959228122f7c85bef1964e3";
      fetchSubmodules = false;
      sha256 = "sha256-9YLJm/L13gTktb6VIkz2W/60cothFtF7feiKd26R5lo=";
    };
  };
  "'plugin-nvim-lightbulb'" = {
    pname = "'plugin-nvim-lightbulb'";
    version = "56b9ce31ec9d09d560fe8787c0920f76bc208297";
    src = fetchFromGitHub {
      owner = "kosayoda";
      repo = "nvim-lightbulb";
      rev = "56b9ce31ec9d09d560fe8787c0920f76bc208297";
      fetchSubmodules = false;
      sha256 = "sha256-nw6H/dS4dHdrobnrfJVa8urWrMnbTWrA5bQJy9xbKXY=";
    };
  };
  "'plugin-nvim-lspconfig'" = {
    pname = "'plugin-nvim-lspconfig'";
    version = "0fd98b0d01bfc5603e56a959acb8e875e4039ac7";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "0fd98b0d01bfc5603e56a959acb8e875e4039ac7";
      fetchSubmodules = false;
      sha256 = "sha256-BJgfRZMdhiZaX/avRZg9Ppd7N6VoOpqOS/XM4uqwM3Y=";
    };
  };
  "'plugin-nvim-tetris'" = {
    pname = "'plugin-nvim-tetris'";
    version = "d17c99fb527ada98ffb0212ffc87ccda6fd4f7d9";
    src = fetchFromGitHub {
      owner = "alec-gibson";
      repo = "nvim-tetris";
      rev = "d17c99fb527ada98ffb0212ffc87ccda6fd4f7d9";
      fetchSubmodules = false;
      sha256 = "sha256-+69Fq5aMMzg9nV05rZxlLTFwQmDyN5/5HmuL2SGu9xQ=";
    };
  };
  "'plugin-nvim-tree.lua'" = {
    pname = "'plugin-nvim-tree.lua'";
    version = "e38e061710c593d9b88c8ebb2c48f2842c89dc31";
    src = fetchFromGitHub {
      owner = "kyazdani42";
      repo = "nvim-tree.lua";
      rev = "e38e061710c593d9b88c8ebb2c48f2842c89dc31";
      fetchSubmodules = false;
      sha256 = "sha256-TZeg/FkUBooziWhpWojfGBQF0YmX999ni9RxO+RZdMQ=";
    };
  };
  "'plugin-nvim-treesitter'" = {
    pname = "'plugin-nvim-treesitter'";
    version = "24caa23402247cf03cfcdd54de8cdb8ed00690ba";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "24caa23402247cf03cfcdd54de8cdb8ed00690ba";
      fetchSubmodules = false;
      sha256 = "sha256-taM3HGP0BD1bOzFu4TF9iDT2EhoohV2FkXy0/TVbIDg=";
    };
  };
  "'plugin-nvim-treesitter-refactor'" = {
    pname = "'plugin-nvim-treesitter-refactor'";
    version = "75f5895cc662d61eb919da8050b7a0124400d589";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter-refactor";
      rev = "75f5895cc662d61eb919da8050b7a0124400d589";
      fetchSubmodules = false;
      sha256 = "sha256-8iAwtoMqh+2ef8qooxBFzm1eAm+P+8IKjjepV4n/+vI=";
    };
  };
  "'plugin-nvim-treesitter-textobjects'" = {
    pname = "'plugin-nvim-treesitter-textobjects'";
    version = "1435ea532a3c9e6ea48ed3438fdf48bb37277578";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter-textobjects";
      rev = "1435ea532a3c9e6ea48ed3438fdf48bb37277578";
      fetchSubmodules = false;
      sha256 = "sha256-18SXROuUU3wkm1h5Yj6eAbNjHsOZXDs68UzUKFt0cNQ=";
    };
  };
  "'plugin-nvim-ts-autotag'" = {
    pname = "'plugin-nvim-ts-autotag'";
    version = "fdefe46c6807441460f11f11a167a2baf8e4534b";
    src = fetchFromGitHub {
      owner = "windwp";
      repo = "nvim-ts-autotag";
      rev = "fdefe46c6807441460f11f11a167a2baf8e4534b";
      fetchSubmodules = false;
      sha256 = "sha256-ltGiYNXWpWSI5RrWTVR+k6SZjcZbsHtH5m9uHTMKnzM=";
    };
  };
  "'plugin-nvim-ts-context-commentstring'" = {
    pname = "'plugin-nvim-ts-context-commentstring'";
    version = "32d9627123321db65a4f158b72b757bcaef1a3f4";
    src = fetchFromGitHub {
      owner = "JoosepAlviste";
      repo = "nvim-ts-context-commentstring";
      rev = "32d9627123321db65a4f158b72b757bcaef1a3f4";
      fetchSubmodules = false;
      sha256 = "sha256-l7T8D+JSwvdmrnX9LNJJMtsDeZwU2gG7k5q1PoHFzZw=";
    };
  };
  "'plugin-nvim-web-devicons'" = {
    pname = "'plugin-nvim-web-devicons'";
    version = "3b1b794bc17b7ac3df3ae471f1c18f18d1a0f958";
    src = fetchFromGitHub {
      owner = "kyazdani42";
      repo = "nvim-web-devicons";
      rev = "3b1b794bc17b7ac3df3ae471f1c18f18d1a0f958";
      fetchSubmodules = false;
      sha256 = "sha256-hxujmUwNtDAXd6JCxBpvPpOzEENQSOYepS7fwmbZufs=";
    };
  };
  "'plugin-one-small-step-for-vimkind'" = {
    pname = "'plugin-one-small-step-for-vimkind'";
    version = "4ca4df5533da67e136fce4a906e33634889d6d76";
    src = fetchFromGitHub {
      owner = "jbyuki";
      repo = "one-small-step-for-vimkind";
      rev = "4ca4df5533da67e136fce4a906e33634889d6d76";
      fetchSubmodules = false;
      sha256 = "sha256-oolCJazBRhsISQ12LHIK1vOlmrxRifpUJ7TqIYOq3YU=";
    };
  };
  "'plugin-packer.nvim'" = {
    pname = "'plugin-packer.nvim'";
    version = "6afb67460283f0e990d35d229fd38fdc04063e0a";
    src = fetchFromGitHub {
      owner = "wbthomason";
      repo = "packer.nvim";
      rev = "6afb67460283f0e990d35d229fd38fdc04063e0a";
      fetchSubmodules = false;
      sha256 = "sha256-CiDvG7OFg6T/e0xPm7u1rCSnnPwSLATYtjhEw0jlp/M=";
    };
  };
  "'plugin-playground'" = {
    pname = "'plugin-playground'";
    version = "1290fdf6f2f0189eb3b4ce8073d3fda6a3658376";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "playground";
      rev = "1290fdf6f2f0189eb3b4ce8073d3fda6a3658376";
      fetchSubmodules = false;
      sha256 = "sha256-oQR0aW/4sUWIA9nBWPOJtZ/T1nQS4MQAX2SJoQqr9vs=";
    };
  };
  "'plugin-plenary.nvim'" = {
    pname = "'plugin-plenary.nvim'";
    version = "4b7e52044bbb84242158d977a50c4cbcd85070c7";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "4b7e52044bbb84242158d977a50c4cbcd85070c7";
      fetchSubmodules = false;
      sha256 = "sha256-lIdBrVpi+vUudeotjFAuw4C0VT8TPoFE9cVVAQEsAYU=";
    };
  };
  "'plugin-presence.nvim'" = {
    pname = "'plugin-presence.nvim'";
    version = "c1c54758824cbecd4e18065d37191f7666fdd097";
    src = fetchFromGitHub {
      owner = "andweeb";
      repo = "presence.nvim";
      rev = "c1c54758824cbecd4e18065d37191f7666fdd097";
      fetchSubmodules = false;
      sha256 = "sha256-v7/fN+NWsnR0APs23nX+kgeje9AlZ3aWy2H1JG57Q0g=";
    };
  };
  "'plugin-project.nvim'" = {
    pname = "'plugin-project.nvim'";
    version = "685bc8e3890d2feb07ccf919522c97f7d33b94e4";
    src = fetchFromGitHub {
      owner = "ahmedkhalf";
      repo = "project.nvim";
      rev = "685bc8e3890d2feb07ccf919522c97f7d33b94e4";
      fetchSubmodules = false;
      sha256 = "sha256-fW4ztvYpeXTC0DbkZS4usG/KENiMJG/sWVTD4e8k42g=";
    };
  };
  "'plugin-rust-tools.nvim'" = {
    pname = "'plugin-rust-tools.nvim'";
    version = "99fd1238c6068d0637df30b6cee9a264334015e9";
    src = fetchFromGitHub {
      owner = "simrat39";
      repo = "rust-tools.nvim";
      rev = "99fd1238c6068d0637df30b6cee9a264334015e9";
      fetchSubmodules = false;
      sha256 = "sha256-7lmLg2ePoeBMHewfgRAt79HMNAF3HWns1PKTe46cJXk=";
    };
  };
  "'plugin-scope.nvim'" = {
    pname = "'plugin-scope.nvim'";
    version = "2db6d31de8e3a98d2b41c0f0d1f5dc299ee76875";
    src = fetchFromGitHub {
      owner = "tiagovla";
      repo = "scope.nvim";
      rev = "2db6d31de8e3a98d2b41c0f0d1f5dc299ee76875";
      fetchSubmodules = false;
      sha256 = "sha256-BdX+C5KBHZcFgDG2fXvhMl2Gp/6ffJWEBvA/JvVWh4I=";
    };
  };
  "'plugin-sidebar.nvim'" = {
    pname = "'plugin-sidebar.nvim'";
    version = "990ce5f562c9125283ccac5473235b1a56fea6dc";
    src = fetchFromGitHub {
      owner = "sidebar-nvim";
      repo = "sidebar.nvim";
      rev = "990ce5f562c9125283ccac5473235b1a56fea6dc";
      fetchSubmodules = false;
      sha256 = "sha256-/6q/W7fWXlJ2B9o4v+0gg2QjhzRC/Iws+Ez6yyL1bqI=";
    };
  };
  "'plugin-sort.nvim'" = {
    pname = "'plugin-sort.nvim'";
    version = "9e4065625317128f6a1c826f4a36f9b47600417a";
    src = fetchFromGitHub {
      owner = "sQVe";
      repo = "sort.nvim";
      rev = "9e4065625317128f6a1c826f4a36f9b47600417a";
      fetchSubmodules = false;
      sha256 = "sha256-1OhGO9lIZ2iTCgV1+bLZf7qZoo+ZDMKmjPHgBWYAmDE=";
    };
  };
  "'plugin-telescope.nvim'" = {
    pname = "'plugin-telescope.nvim'";
    version = "7a4ffef931769c3fe7544214ed7ffde5852653f6";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope.nvim";
      rev = "7a4ffef931769c3fe7544214ed7ffde5852653f6";
      fetchSubmodules = false;
      sha256 = "sha256-U5H4bpQ087pCS/HoHNgrbsH9wARdccDpXLxY++75TFg=";
    };
  };
  "'plugin-treesitter-unit'" = {
    pname = "'plugin-treesitter-unit'";
    version = "89968a1f8c72427691088e6d09d26a52c2ddc6f4";
    src = fetchFromGitHub {
      owner = "David-Kunz";
      repo = "treesitter-unit";
      rev = "89968a1f8c72427691088e6d09d26a52c2ddc6f4";
      fetchSubmodules = false;
      sha256 = "sha256-ahIar02sDhMbRpXVTBQSn134PLmMiubPUOg8Chq7gsk=";
    };
  };
  "'plugin-trouble.nvim'" = {
    pname = "'plugin-trouble.nvim'";
    version = "897542f90050c3230856bc6e45de58b94c700bbf";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "trouble.nvim";
      rev = "897542f90050c3230856bc6e45de58b94c700bbf";
      fetchSubmodules = false;
      sha256 = "sha256-8IJB4cIT85GkManiRSelGEMGudnGwZ5Vr+CJwTv40SY=";
    };
  };
  "'plugin-twilight.nvim'" = {
    pname = "'plugin-twilight.nvim'";
    version = "1ffa6a4d89fb2fbb784c6674044bf54f1fca936f";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "twilight.nvim";
      rev = "1ffa6a4d89fb2fbb784c6674044bf54f1fca936f";
      fetchSubmodules = false;
      sha256 = "sha256-ryjYff6ljCTx9wwq3idl5g34Kjr4zbOJLON3oYqvgas=";
    };
  };
  "'plugin-vim-eunuch'" = {
    pname = "'plugin-vim-eunuch'";
    version = "291ef1f8c8996ca7715df1032a35a27b12d7b5cf";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-eunuch";
      rev = "291ef1f8c8996ca7715df1032a35a27b12d7b5cf";
      fetchSubmodules = false;
      sha256 = "sha256-t7D6vkEmhVDKdxqvHQ6811FENu/qM6MkrLl8lGADxDs=";
    };
  };
  "'plugin-vim-floaterm'" = {
    pname = "'plugin-vim-floaterm'";
    version = "280b34a0760801168a67f952542b6c49292aa5f3";
    src = fetchFromGitHub {
      owner = "voldikss";
      repo = "vim-floaterm";
      rev = "280b34a0760801168a67f952542b6c49292aa5f3";
      fetchSubmodules = false;
      sha256 = "sha256-nI0p1bwGuWqf6S7xr7aX8kXDY5xGP1Ip8jiaOfFCC6Y=";
    };
  };
  "'plugin-vim-repeat'" = {
    pname = "'plugin-vim-repeat'";
    version = "24afe922e6a05891756ecf331f39a1f6743d3d5a";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-repeat";
      rev = "24afe922e6a05891756ecf331f39a1f6743d3d5a";
      fetchSubmodules = false;
      sha256 = "sha256-8rfZa3uKXB3TRCqaDHZ6DfzNbm7WaYnLvmTNzYtnKHg=";
    };
  };
  "'plugin-vim-sleuth'" = {
    pname = "'plugin-vim-sleuth'";
    version = "8332f123a63c739c870c96907d987cc3ff719d24";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-sleuth";
      rev = "8332f123a63c739c870c96907d987cc3ff719d24";
      fetchSubmodules = false;
      sha256 = "sha256-764rtPxcdSs5j0yo4atPNqduEe4GvryOmaIJtCqxVJU=";
    };
  };
  "'plugin-vim-startuptime'" = {
    pname = "'plugin-vim-startuptime'";
    version = "1acb5fa4aa29a24c36d559474b672cda9b9a9b6d";
    src = fetchFromGitHub {
      owner = "dstein64";
      repo = "vim-startuptime";
      rev = "1acb5fa4aa29a24c36d559474b672cda9b9a9b6d";
      fetchSubmodules = false;
      sha256 = "sha256-MvYkR7Ej/hAZ4vcYhfCuqsFmTe0a28L8gbr8NwtRb+c=";
    };
  };
  "'plugin-vim-surround'" = {
    pname = "'plugin-vim-surround'";
    version = "3d188ed2113431cf8dac77be61b842acb64433d9";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-surround";
      rev = "3d188ed2113431cf8dac77be61b842acb64433d9";
      fetchSubmodules = false;
      sha256 = "sha256-DZE5tkmnT+lAvx/RQHaDEgEJXRKsy56KJY919xiH1lE=";
    };
  };
  "'plugin-vimtex'" = {
    pname = "'plugin-vimtex'";
    version = "b2a69e8f780709a4637f6e2fe809d6bd2a39af52";
    src = fetchFromGitHub {
      owner = "lervag";
      repo = "vimtex";
      rev = "b2a69e8f780709a4637f6e2fe809d6bd2a39af52";
      fetchSubmodules = false;
      sha256 = "sha256-CrQL+GkzspHRTxQQ5h7VM6nYBpm/u8ONFwLT12xbBoY=";
    };
  };
  "'plugin-which-key.nvim'" = {
    pname = "'plugin-which-key.nvim'";
    version = "61553aeb3d5ca8c11eea8be6eadf478062982ac9";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "which-key.nvim";
      rev = "61553aeb3d5ca8c11eea8be6eadf478062982ac9";
      fetchSubmodules = false;
      sha256 = "sha256-IbJP6j+M+POPhX4YbewTJiSoELvDo6y+vF0RREqqm4c=";
    };
  };
  "'plugin-zen-mode.nvim'" = {
    pname = "'plugin-zen-mode.nvim'";
    version = "6f5702db4fd4a4c9a212f8de3b7b982f3d93b03c";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "zen-mode.nvim";
      rev = "6f5702db4fd4a4c9a212f8de3b7b982f3d93b03c";
      fetchSubmodules = false;
      sha256 = "sha256-n69FYW16uns+OXTsPCUeEPF5Z3dOJq997O/XTttpKBI=";
    };
  };
  "'plugin-zoxide.vim'" = {
    pname = "'plugin-zoxide.vim'";
    version = "7add42b0474b07c206c94d1693997e52d25c5fec";
    src = fetchFromGitHub {
      owner = "nanotee";
      repo = "zoxide.vim";
      rev = "7add42b0474b07c206c94d1693997e52d25c5fec";
      fetchSubmodules = false;
      sha256 = "sha256-GZZIBCQyfLLz7iBXhTH++LGSHz/NOgOB4svb5MgkWbM=";
    };
  };
  tree-sitter-bash = {
    pname = "tree-sitter-bash";
    version = "77cf8a7cab8904baf1a721762e012644ac1d4c7b";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-bash";
      rev = "77cf8a7cab8904baf1a721762e012644ac1d4c7b";
      fetchSubmodules = false;
      sha256 = "sha256-UPMJ7iL8Y0NkAHtPDrkTjG1qFwr8rXuGqvsG+LTWqEY=";
    };
  };
  tree-sitter-kotlin = {
    pname = "tree-sitter-kotlin";
    version = "b953dbdd05257fcb2b64bc4d9c1578fac12e3c28";
    src = fetchFromGitHub {
      owner = "fwcd";
      repo = "tree-sitter-kotlin";
      rev = "b953dbdd05257fcb2b64bc4d9c1578fac12e3c28";
      fetchSubmodules = false;
      sha256 = "sha256-xTbRn7bDN6FR9UOzw43RVHIahI/DFjwLGQj3cYoPurY=";
    };
  };
  tree-sitter-norg = {
    pname = "tree-sitter-norg";
    version = "8ad20059c6f128861c4506fff866150ffee1d6f4";
    src = fetchFromGitHub {
      owner = "nvim-neorg";
      repo = "tree-sitter-norg";
      rev = "8ad20059c6f128861c4506fff866150ffee1d6f4";
      fetchSubmodules = false;
      sha256 = "sha256-1cKH3k/nbZhZleINZ91M+glG1m2SlBJR/AP7mz/SAvI=";
    };
  };
  tree-sitter-norg-meta = {
    pname = "tree-sitter-norg-meta";
    version = "8e1a9008eb9492e95eb9a65ab0ec0419cfa9c4c7";
    src = fetchFromGitHub {
      owner = "nvim-neorg";
      repo = "tree-sitter-norg-meta";
      rev = "8e1a9008eb9492e95eb9a65ab0ec0419cfa9c4c7";
      fetchSubmodules = false;
      sha256 = "sha256-1gOTQdqB/TpaJ2ClNY+/Gqsj7TkCgv9CNiX97oF8PGo=";
    };
  };
  tree-sitter-norg-table = {
    pname = "tree-sitter-norg-table";
    version = "f354ea343b8803948e6e1df36eb586e31c529900";
    src = fetchFromGitHub {
      owner = "nvim-neorg";
      repo = "tree-sitter-norg-table";
      rev = "f354ea343b8803948e6e1df36eb586e31c529900";
      fetchSubmodules = false;
      sha256 = "sha256-xTH4LmqhtfyN9JGQdquJLQz1McZQItdEY5HpJxbuYC0=";
    };
  };
  tree-sitter-sql = {
    pname = "tree-sitter-sql";
    version = "4f1b91246b43190e34957d9de9a0f3625879ba33";
    src = fetchFromGitHub {
      owner = "derekstride";
      repo = "tree-sitter-sql";
      rev = "4f1b91246b43190e34957d9de9a0f3625879ba33";
      fetchSubmodules = false;
      sha256 = "sha256-g1dQ897JQwthConYMlGY25hsypr4weDsDCOWyafriw8=";
    };
  };
  tree-sitter-vala = {
    pname = "tree-sitter-vala";
    version = "8f690bfa639f2b83d1fb938ed3dd98a7ba453e8b";
    src = fetchFromGitHub {
      owner = "vala-lang";
      repo = "tree-sitter-vala";
      rev = "8f690bfa639f2b83d1fb938ed3dd98a7ba453e8b";
      fetchSubmodules = false;
      sha256 = "sha256-YZTE3PkBPCEkMXnLC0HSQ86v5+3/J7/ETDQp8eguFW8=";
    };
  };
}
