# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  "'plugin-Comment.nvim'" = {
    pname = "'plugin-Comment.nvim'";
    version = "e89df176e8b38e931b7e71a470f923a317976d86";
    src = fetchFromGitHub {
      owner = "numToStr";
      repo = "Comment.nvim";
      rev = "e89df176e8b38e931b7e71a470f923a317976d86";
      fetchSubmodules = false;
      sha256 = "sha256-HVel6DCxXP6f29jQF+32uRcWMiv/Z1g+Insu3pc5alQ=";
    };
    date = "2023-01-07";
  };
  "'plugin-FTerm.nvim'" = {
    pname = "'plugin-FTerm.nvim'";
    version = "d1320892cc2ebab472935242d9d992a2c9570180";
    src = fetchFromGitHub {
      owner = "numToStr";
      repo = "FTerm.nvim";
      rev = "d1320892cc2ebab472935242d9d992a2c9570180";
      fetchSubmodules = false;
      sha256 = "sha256-fCtAs6qsvWOYRp2Z1AwQa2ByUZcUCMKfuYBoNTP7EeY=";
    };
    date = "2022-11-13";
  };
  "'plugin-LuaSnip'" = {
    pname = "'plugin-LuaSnip'";
    version = "45670282dc861b51c4e028e6930c75371fe0b88f";
    src = fetchFromGitHub {
      owner = "L3MON4D3";
      repo = "LuaSnip";
      rev = "45670282dc861b51c4e028e6930c75371fe0b88f";
      fetchSubmodules = false;
      sha256 = "sha256-jNQLZRc0axG8n7Kr6ub/LaiGTfFs23z/iDMkZvrPXyk=";
    };
    date = "2023-01-16";
  };
  "'plugin-SmoothCursor.nvim'" = {
    pname = "'plugin-SmoothCursor.nvim'";
    version = "e3e2366715cb921cb4a49cde017e04e8e4b7b5db";
    src = fetchFromGitHub {
      owner = "gen740";
      repo = "SmoothCursor.nvim";
      rev = "e3e2366715cb921cb4a49cde017e04e8e4b7b5db";
      fetchSubmodules = false;
      sha256 = "sha256-m4/UcWQ1uSyr8Gq//jDg7As1TO97LRRlbZ3CPndD4Dc=";
    };
    date = "2023-01-13";
  };
  "'plugin-auto-save.nvim'" = {
    pname = "'plugin-auto-save.nvim'";
    version = "979b6c82f60cfa80f4cf437d77446d0ded0addf0";
    src = fetchFromGitHub {
      owner = "Pocco81";
      repo = "auto-save.nvim";
      rev = "979b6c82f60cfa80f4cf437d77446d0ded0addf0";
      fetchSubmodules = false;
      sha256 = "sha256-bWGil73YiCKZEaY7IuUOIU4Q7k7qCMjSeQ4I+cAVe44=";
    };
    date = "2022-11-01";
  };
  "'plugin-bufferline.nvim'" = {
    pname = "'plugin-bufferline.nvim'";
    version = "c7492a76ce8218e3335f027af44930576b561013";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "bufferline.nvim";
      rev = "c7492a76ce8218e3335f027af44930576b561013";
      fetchSubmodules = false;
      sha256 = "sha256-q8nwZRN97Sfrr7lHtNYwGdbS63obMOAxFFs/gSvqbqM=";
    };
    date = "2022-12-24";
  };
  "'plugin-carbon.nvim'" = {
    pname = "'plugin-carbon.nvim'";
    version = "ed16e9872a3ae7e0827d895798503b92a7ab1bfa";
    src = fetchFromGitHub {
      owner = "SidOfc";
      repo = "carbon.nvim";
      rev = "ed16e9872a3ae7e0827d895798503b92a7ab1bfa";
      fetchSubmodules = false;
      sha256 = "sha256-kSgv7otwLOVp3VmtFdEMEUcsmI6/wY1QSfSzh6WtJ/w=";
    };
    date = "2023-01-14";
  };
  "'plugin-circles.nvim'" = {
    pname = "'plugin-circles.nvim'";
    version = "91ae7e0ddf95e1984528cf3129879f4841bcbc82";
    src = fetchFromGitHub {
      owner = "projekt0n";
      repo = "circles.nvim";
      rev = "91ae7e0ddf95e1984528cf3129879f4841bcbc82";
      fetchSubmodules = false;
      sha256 = "sha256-FUo7M42UHW3HWigDHZMRpQOKePktvMoOV7h9UgVMvnI=";
    };
    date = "2022-11-28";
  };
  "'plugin-cmp-buffer'" = {
    pname = "'plugin-cmp-buffer'";
    version = "3022dbc9166796b644a841a02de8dd1cc1d311fa";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-buffer";
      rev = "3022dbc9166796b644a841a02de8dd1cc1d311fa";
      fetchSubmodules = false;
      sha256 = "sha256-dG4U7MtnXThoa/PD+qFtCt76MQ14V1wX8GMYcvxEnbM=";
    };
    date = "2022-08-10";
  };
  "'plugin-cmp-calc'" = {
    pname = "'plugin-cmp-calc'";
    version = "50792f34a628ea6eb31d2c90e8df174671e4e7a0";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-calc";
      rev = "50792f34a628ea6eb31d2c90e8df174671e4e7a0";
      fetchSubmodules = false;
      sha256 = "sha256-GqTY4/Puk4pikjeyyMcJ8wzgb1IC7Cf4gcXx/XXmgP4=";
    };
    date = "2022-11-16";
  };
  "'plugin-cmp-cmdline'" = {
    pname = "'plugin-cmp-cmdline'";
    version = "23c51b2a3c00f6abc4e922dbd7c3b9aca6992063";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-cmdline";
      rev = "23c51b2a3c00f6abc4e922dbd7c3b9aca6992063";
      fetchSubmodules = false;
      sha256 = "sha256-hzLiqPMU0tDQ4MTwKxvb3gY2JdD5KwqltGYckuSOzm0=";
    };
    date = "2022-11-27";
  };
  "'plugin-cmp-dap'" = {
    pname = "'plugin-cmp-dap'";
    version = "d16f14a210cd28988b97ca8339d504533b7e09a4";
    src = fetchFromGitHub {
      owner = "rcarriga";
      repo = "cmp-dap";
      rev = "d16f14a210cd28988b97ca8339d504533b7e09a4";
      fetchSubmodules = false;
      sha256 = "sha256-w+gGaZxXjb2B0dMXhfduEQKtO5CmQnuUdh4otpcsFuc=";
    };
    date = "2022-11-13";
  };
  "'plugin-cmp-nvim-lsp'" = {
    pname = "'plugin-cmp-nvim-lsp'";
    version = "59224771f91b86d1de12570b4070fe4ad7cd1eeb";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-nvim-lsp";
      rev = "59224771f91b86d1de12570b4070fe4ad7cd1eeb";
      fetchSubmodules = false;
      sha256 = "sha256-Mqkp8IH/laUx0cK7S0BjusTT+OtOOJOamZM4+93RHdU=";
    };
    date = "2022-11-16";
  };
  "'plugin-cmp-omni'" = {
    pname = "'plugin-cmp-omni'";
    version = "8457e4144ea2fc5efbadb7d22250d5ee8f8862ba";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-omni";
      rev = "8457e4144ea2fc5efbadb7d22250d5ee8f8862ba";
      fetchSubmodules = false;
      sha256 = "sha256-WXW9DPogGNqdhF3tAlztdl+1ct6spWQbNztbIxZyGAc=";
    };
    date = "2022-11-17";
  };
  "'plugin-cmp-path'" = {
    pname = "'plugin-cmp-path'";
    version = "91ff86cd9c29299a64f968ebb45846c485725f23";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-path";
      rev = "91ff86cd9c29299a64f968ebb45846c485725f23";
      fetchSubmodules = false;
      sha256 = "sha256-thppiiV3wjIaZnAXmsh7j3DUc6ceSCvGzviwFUnoPaI=";
    };
    date = "2022-10-03";
  };
  "'plugin-cmp_luasnip'" = {
    pname = "'plugin-cmp_luasnip'";
    version = "18095520391186d634a0045dacaa346291096566";
    src = fetchFromGitHub {
      owner = "saadparwaiz1";
      repo = "cmp_luasnip";
      rev = "18095520391186d634a0045dacaa346291096566";
      fetchSubmodules = false;
      sha256 = "sha256-Z5SPy3j2oHFxJ7bK8DP8Q/oRyLEMlnWyIfDaQcNVIS0=";
    };
    date = "2022-10-28";
  };
  "'plugin-dial.nvim'" = {
    pname = "'plugin-dial.nvim'";
    version = "dbcfd4510d31884d444ec33a4453d0f06ad4a5eb";
    src = fetchFromGitHub {
      owner = "monaqa";
      repo = "dial.nvim";
      rev = "dbcfd4510d31884d444ec33a4453d0f06ad4a5eb";
      fetchSubmodules = false;
      sha256 = "sha256-wYTBe4nkoto0rIeb0cFdkPCGj+JMWjMWvOqFoCZknOE=";
    };
    date = "2023-01-16";
  };
  "'plugin-diffview.nvim'" = {
    pname = "'plugin-diffview.nvim'";
    version = "5bbcf162d03287296fe393f88da6065db3cf9fd0";
    src = fetchFromGitHub {
      owner = "sindrets";
      repo = "diffview.nvim";
      rev = "5bbcf162d03287296fe393f88da6065db3cf9fd0";
      fetchSubmodules = false;
      sha256 = "sha256-4Q8/KdcB2g8EyvMs4AwS3tTX6/Z8gAYRvrXIpkXduFI=";
    };
    date = "2023-01-15";
  };
  "'plugin-dressing.nvim'" = {
    pname = "'plugin-dressing.nvim'";
    version = "4436d6f41e2f6b8ada57588acd1a9f8b3d21453c";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "dressing.nvim";
      rev = "4436d6f41e2f6b8ada57588acd1a9f8b3d21453c";
      fetchSubmodules = false;
      sha256 = "sha256-wZCbqn44wrnqTVJWlkjgGQ0LkB+RbpvH5wn0cbHDncc=";
    };
    date = "2022-12-12";
  };
  "'plugin-duck.nvim'" = {
    pname = "'plugin-duck.nvim'";
    version = "b1a3b4e52eec886bf4ce5ed692a2162d504d9632";
    src = fetchFromGitHub {
      owner = "tamton-aquib";
      repo = "duck.nvim";
      rev = "b1a3b4e52eec886bf4ce5ed692a2162d504d9632";
      fetchSubmodules = false;
      sha256 = "sha256-H+Ufqb3a6Re4eo/ByYmwrzfmHTAU8irZzF/WcoJOjDI=";
    };
    date = "2022-11-30";
  };
  "'plugin-editorconfig.nvim'" = {
    pname = "'plugin-editorconfig.nvim'";
    version = "5b9e303e1d6f7abfe616ce4cc8d3fffc554790bf";
    src = fetchFromGitHub {
      owner = "gpanders";
      repo = "editorconfig.nvim";
      rev = "5b9e303e1d6f7abfe616ce4cc8d3fffc554790bf";
      fetchSubmodules = false;
      sha256 = "sha256-pR57tITdVGF4luEmmRYv/XFb35E3KDfcgYRijkPAc+Y=";
    };
    date = "2023-01-10";
  };
  "'plugin-flutter-tools.nvim'" = {
    pname = "'plugin-flutter-tools.nvim'";
    version = "ae0be3cef35c0cb41d6c7f814a19b3402d50fd7a";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "flutter-tools.nvim";
      rev = "ae0be3cef35c0cb41d6c7f814a19b3402d50fd7a";
      fetchSubmodules = false;
      sha256 = "sha256-O7t8ySnDwGqRTioG1uffDwlbJTM2c1HZVXlV+H5s0Xo=";
    };
    date = "2023-01-01";
  };
  "'plugin-friendly-snippets'" = {
    pname = "'plugin-friendly-snippets'";
    version = "7ab483b355613ef4f74189c7789278d765724d12";
    src = fetchFromGitHub {
      owner = "rafamadriz";
      repo = "friendly-snippets";
      rev = "7ab483b355613ef4f74189c7789278d765724d12";
      fetchSubmodules = false;
      sha256 = "sha256-dF7anJxjTojTVn0v+RSsWjsQjsixHaTxhWEq5qD6T4Y=";
    };
    date = "2023-01-13";
  };
  "'plugin-github-nvim-theme'" = {
    pname = "'plugin-github-nvim-theme'";
    version = "24c8706c9ad26b944f5a76dea999dca8708f252e";
    src = fetchFromGitHub {
      owner = "projekt0n";
      repo = "github-nvim-theme";
      rev = "24c8706c9ad26b944f5a76dea999dca8708f252e";
      fetchSubmodules = false;
      sha256 = "sha256-Qm9ffdkHfG5+PLQ8PbOeFMywBbKVGqX8886clQbJzyg=";
    };
    date = "2023-01-16";
  };
  "'plugin-gitsigns.nvim'" = {
    pname = "'plugin-gitsigns.nvim'";
    version = "addd6e174a85fc1c4007ab0b65d77e6555b417bf";
    src = fetchFromGitHub {
      owner = "lewis6991";
      repo = "gitsigns.nvim";
      rev = "addd6e174a85fc1c4007ab0b65d77e6555b417bf";
      fetchSubmodules = false;
      sha256 = "sha256-daiqkwRO9NRrU6zf87m2KQayvuHSQ0OeEay39TWa9iU=";
    };
    date = "2023-01-12";
  };
  "'plugin-guess-indent.nvim'" = {
    pname = "'plugin-guess-indent.nvim'";
    version = "c37467baa1a51b74ed767cbe0540fce44e03d828";
    src = fetchFromGitHub {
      owner = "NMAC427";
      repo = "guess-indent.nvim";
      rev = "c37467baa1a51b74ed767cbe0540fce44e03d828";
      fetchSubmodules = false;
      sha256 = "sha256-K+9gW3SIYHKtJkSvbHeT1frFGHk9zNP0oc8nrHRPy4U=";
    };
    date = "2022-07-17";
  };
  "'plugin-haskell-tools.nvim'" = {
    pname = "'plugin-haskell-tools.nvim'";
    version = "5f999135e8fa177d3161c387a153209c18c4ced4";
    src = fetchFromGitHub {
      owner = "MrcJkb";
      repo = "haskell-tools.nvim";
      rev = "5f999135e8fa177d3161c387a153209c18c4ced4";
      fetchSubmodules = false;
      sha256 = "sha256-dPKBG2PRe8ExsyBycIIwVRHg2fMU4AHy/sR8z6lMtVQ=";
    };
    date = "2023-01-16";
  };
  "'plugin-highlight-current-n.nvim'" = {
    pname = "'plugin-highlight-current-n.nvim'";
    version = "bac803d821d06d5f1e58b31af1cf2e5f9a5fb4ad";
    src = fetchFromGitHub {
      owner = "rktjmp";
      repo = "highlight-current-n.nvim";
      rev = "bac803d821d06d5f1e58b31af1cf2e5f9a5fb4ad";
      fetchSubmodules = false;
      sha256 = "sha256-XE9tpjxU20Lhyp5rOsudLcpRkRHzY/d/FNbn02afXdQ=";
    };
    date = "2022-12-03";
  };
  "'plugin-indent-blankline.nvim'" = {
    pname = "'plugin-indent-blankline.nvim'";
    version = "c4c203c3e8a595bc333abaf168fcb10c13ed5fb7";
    src = fetchFromGitHub {
      owner = "lukas-reineke";
      repo = "indent-blankline.nvim";
      rev = "c4c203c3e8a595bc333abaf168fcb10c13ed5fb7";
      fetchSubmodules = false;
      sha256 = "sha256-BvRE4l10Ruz3j4JJwSAKuE9M3vd1blDbEHHlwIB2Vs0=";
    };
    date = "2022-12-08";
  };
  "'plugin-lazy.nvim'" = {
    pname = "'plugin-lazy.nvim'";
    version = "efe72d98e6fb71252bd9a904c00a40ccd54ebf05";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "lazy.nvim";
      rev = "efe72d98e6fb71252bd9a904c00a40ccd54ebf05";
      fetchSubmodules = false;
      sha256 = "sha256-BCekiePaoQEhO8pRJSKMzUfLjihwbXQb1WNvfJYOlSI=";
    };
    date = "2023-01-16";
  };
  "'plugin-leap.nvim'" = {
    pname = "'plugin-leap.nvim'";
    version = "a968ab4250840dc879e805f918b4f3b892310a12";
    src = fetchFromGitHub {
      owner = "ggandor";
      repo = "leap.nvim";
      rev = "a968ab4250840dc879e805f918b4f3b892310a12";
      fetchSubmodules = false;
      sha256 = "sha256-TcNjuFFRiBLT6oxOPqSl06oUS2NOCnBlldf65b2GOfo=";
    };
    date = "2023-01-03";
  };
  "'plugin-lsp-format.nvim'" = {
    pname = "'plugin-lsp-format.nvim'";
    version = "ca0df5c8544e51517209ea7b86ecc522c98d4f0a";
    src = fetchFromGitHub {
      owner = "lukas-reineke";
      repo = "lsp-format.nvim";
      rev = "ca0df5c8544e51517209ea7b86ecc522c98d4f0a";
      fetchSubmodules = false;
      sha256 = "sha256-UeeM+rHDjsZS27L2Orh+doB6eo6YNV8gb0yLs0PjkLA=";
    };
    date = "2022-11-25";
  };
  "'plugin-lsp_signature.nvim'" = {
    pname = "'plugin-lsp_signature.nvim'";
    version = "1979f1118e2b38084e7c148f279eed6e9300a342";
    src = fetchFromGitHub {
      owner = "ray-x";
      repo = "lsp_signature.nvim";
      rev = "1979f1118e2b38084e7c148f279eed6e9300a342";
      fetchSubmodules = false;
      sha256 = "sha256-3p+wnRDBnt0Ey5lJxUUMLLfRdYR0KMue6BW43uIlKDY=";
    };
    date = "2022-12-24";
  };
  "'plugin-lspkind-nvim'" = {
    pname = "'plugin-lspkind-nvim'";
    version = "c68b3a003483cf382428a43035079f78474cd11e";
    src = fetchFromGitHub {
      owner = "onsails";
      repo = "lspkind-nvim";
      rev = "c68b3a003483cf382428a43035079f78474cd11e";
      fetchSubmodules = false;
      sha256 = "sha256-WwUQ+O2rIfD4yl0GFx70GsZc9nnhS7b2KWfNdaXCLmM=";
    };
    date = "2022-09-22";
  };
  "'plugin-ltex_extra.nvim'" = {
    pname = "'plugin-ltex_extra.nvim'";
    version = "aed3216f8d56d68085e2e3edd62f9236bc4d622b";
    src = fetchFromGitHub {
      owner = "barreiroleo";
      repo = "ltex_extra.nvim";
      rev = "aed3216f8d56d68085e2e3edd62f9236bc4d622b";
      fetchSubmodules = false;
      sha256 = "sha256-970ZA3yEfivaMj2SKNdY8TAqbwc3KhHR6x4c4RUsWqM=";
    };
    date = "2023-01-07";
  };
  "'plugin-lualine.nvim'" = {
    pname = "'plugin-lualine.nvim'";
    version = "0050b308552e45f7128f399886c86afefc3eb988";
    src = fetchFromGitHub {
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "0050b308552e45f7128f399886c86afefc3eb988";
      fetchSubmodules = false;
      sha256 = "sha256-3I9og+/lVRFJSpDVFwp2AM5bMqeP1KF8XB8Nyfpwhok=";
    };
    date = "2023-01-11";
  };
  "'plugin-luasnip-latex-snippets.nvim'" = {
    pname = "'plugin-luasnip-latex-snippets.nvim'";
    version = "d0b9f4f53ed1d3ac3c9ca7abd86d9f55431566aa";
    src = fetchFromGitHub {
      owner = "iurimateus";
      repo = "luasnip-latex-snippets.nvim";
      rev = "d0b9f4f53ed1d3ac3c9ca7abd86d9f55431566aa";
      fetchSubmodules = false;
      sha256 = "sha256-cbFdcXb/7tCDUXT3ynscKgTWyfXv1flEWtc7tev3bMo=";
    };
    date = "2023-01-01";
  };
  "'plugin-lush.nvim'" = {
    pname = "'plugin-lush.nvim'";
    version = "b1e8eb1da3fee95ef31515a73c9eff9bf251088d";
    src = fetchFromGitHub {
      owner = "rktjmp";
      repo = "lush.nvim";
      rev = "b1e8eb1da3fee95ef31515a73c9eff9bf251088d";
      fetchSubmodules = false;
      sha256 = "sha256-+M5tPNuL8OtkIZcB3+5+snygocWPhnXoZzen6gjOd2A=";
    };
    date = "2023-01-03";
  };
  "'plugin-neodev.nvim'" = {
    pname = "'plugin-neodev.nvim'";
    version = "a587f5eeb826c10063d0b961d21a541e7868faf3";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "neodev.nvim";
      rev = "a587f5eeb826c10063d0b961d21a541e7868faf3";
      fetchSubmodules = false;
      sha256 = "sha256-V8e3W/fEpHoyIvRpHkxSPxttxZgVP/Ln9lyQDjY0ImQ=";
    };
    date = "2023-01-15";
  };
  "'plugin-neorg'" = {
    pname = "'plugin-neorg'";
    version = "aa613122f82ca7485b7055937a742b709ed3c576";
    src = fetchFromGitHub {
      owner = "nvim-neorg";
      repo = "neorg";
      rev = "aa613122f82ca7485b7055937a742b709ed3c576";
      fetchSubmodules = false;
      sha256 = "sha256-DORQXb5o+qRSQd7IEHlee4VPG/ZR12WYvQiUnDOpLWM=";
    };
    date = "2023-01-13";
  };
  "'plugin-neorg-telescope'" = {
    pname = "'plugin-neorg-telescope'";
    version = "8d15129818c5dc224be97c9c6350d3386addeac8";
    src = fetchFromGitHub {
      owner = "nvim-neorg";
      repo = "neorg-telescope";
      rev = "8d15129818c5dc224be97c9c6350d3386addeac8";
      fetchSubmodules = false;
      sha256 = "sha256-KDEziW99VyW2RjGV0+JaLSXXZ66WSNVPBNaw6N7Fri0=";
    };
    date = "2022-11-15";
  };
  "'plugin-null-ls.nvim'" = {
    pname = "'plugin-null-ls.nvim'";
    version = "915558963709ea17c5aa246ca1c9786bfee6ddb4";
    src = fetchFromGitHub {
      owner = "jose-elias-alvarez";
      repo = "null-ls.nvim";
      rev = "915558963709ea17c5aa246ca1c9786bfee6ddb4";
      fetchSubmodules = false;
      sha256 = "sha256-gEHFJERS1kmdTjIJPLliM/y5BJgGWcglzsnkFaIUQQg=";
    };
    date = "2023-01-07";
  };
  "'plugin-nvim-autopairs'" = {
    pname = "'plugin-nvim-autopairs'";
    version = "f00eb3b766c370cb34fdabc29c760338ba9e4c6c";
    src = fetchFromGitHub {
      owner = "windwp";
      repo = "nvim-autopairs";
      rev = "f00eb3b766c370cb34fdabc29c760338ba9e4c6c";
      fetchSubmodules = false;
      sha256 = "sha256-C8Apt+TN8iiKT0s000aEn5yReVSlg/o5cXrTPXBN+pA=";
    };
    date = "2023-01-08";
  };
  "'plugin-nvim-cmp'" = {
    pname = "'plugin-nvim-cmp'";
    version = "11a95792a5be0f5a40bab5fc5b670e5b1399a939";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "nvim-cmp";
      rev = "11a95792a5be0f5a40bab5fc5b670e5b1399a939";
      fetchSubmodules = false;
      sha256 = "sha256-3zPU7WsCow4t0LcG5AGOPEEtVyRZDvo6epzVc9MOGZ0=";
    };
    date = "2023-01-06";
  };
  "'plugin-nvim-colorizer.lua'" = {
    pname = "'plugin-nvim-colorizer.lua'";
    version = "36c610a9717cc9ec426a07c8e6bf3b3abcb139d6";
    src = fetchFromGitHub {
      owner = "norcalli";
      repo = "nvim-colorizer.lua";
      rev = "36c610a9717cc9ec426a07c8e6bf3b3abcb139d6";
      fetchSubmodules = false;
      sha256 = "sha256-6YrnItxExL2C8pNIdLd+hXCjsB2MbZANwWkah6dreD8=";
    };
    date = "2020-06-11";
  };
  "'plugin-nvim-dap'" = {
    pname = "'plugin-nvim-dap'";
    version = "5a1479c5d633daa0db06988ed44663f07f10f5dd";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-dap";
      rev = "5a1479c5d633daa0db06988ed44663f07f10f5dd";
      fetchSubmodules = false;
      sha256 = "sha256-1TAtTrhrQIu6vd/PrEowPSHVZqBM91Hd+deGPUGcNFI=";
    };
    date = "2023-01-14";
  };
  "'plugin-nvim-dap-go'" = {
    pname = "'plugin-nvim-dap-go'";
    version = "6f045a72a05a78e4071dd0880f08214a2bb1461b";
    src = fetchFromGitHub {
      owner = "leoluz";
      repo = "nvim-dap-go";
      rev = "6f045a72a05a78e4071dd0880f08214a2bb1461b";
      fetchSubmodules = false;
      sha256 = "sha256-aVJeVP4JqLY8TqxK/H2IqgaE98WwIJIOCI+PhLnsbZQ=";
    };
    date = "2023-01-04";
  };
  "'plugin-nvim-dap-python'" = {
    pname = "'plugin-nvim-dap-python'";
    version = "d4400d075c21ed8fb8e8ac6a5ff56f58f6e93531";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-dap-python";
      rev = "d4400d075c21ed8fb8e8ac6a5ff56f58f6e93531";
      fetchSubmodules = false;
      sha256 = "sha256-oAZR0cKY7RmIy3tNWA2d5CdBxi3NHBSBeYO9U3bukL4=";
    };
    date = "2022-12-18";
  };
  "'plugin-nvim-dap-ui'" = {
    pname = "'plugin-nvim-dap-ui'";
    version = "b80227ea56a48177786904f6322abc8b2dc0bc36";
    src = fetchFromGitHub {
      owner = "rcarriga";
      repo = "nvim-dap-ui";
      rev = "b80227ea56a48177786904f6322abc8b2dc0bc36";
      fetchSubmodules = false;
      sha256 = "sha256-oVpRdIVd2uA+a009ElyLhtASIErV8+0m/WK1UImVSYU=";
    };
    date = "2023-01-11";
  };
  "'plugin-nvim-dap-virtual-text'" = {
    pname = "'plugin-nvim-dap-virtual-text'";
    version = "6d3da4b786d33e35526e089d85b238c08ce78def";
    src = fetchFromGitHub {
      owner = "theHamsta";
      repo = "nvim-dap-virtual-text";
      rev = "6d3da4b786d33e35526e089d85b238c08ce78def";
      fetchSubmodules = false;
      sha256 = "sha256-fKT8UW/cbEhjGqsZFyvZRiUTzlYfmWMiv9xT6zMFpXQ=";
    };
    date = "2023-01-14";
  };
  "'plugin-nvim-gomove'" = {
    pname = "'plugin-nvim-gomove'";
    version = "2b44ae7ac0804f4e3959228122f7c85bef1964e3";
    src = fetchFromGitHub {
      owner = "booperlv";
      repo = "nvim-gomove";
      rev = "2b44ae7ac0804f4e3959228122f7c85bef1964e3";
      fetchSubmodules = false;
      sha256 = "sha256-9YLJm/L13gTktb6VIkz2W/60cothFtF7feiKd26R5lo=";
    };
    date = "2022-07-19";
  };
  "'plugin-nvim-lightbulb'" = {
    pname = "'plugin-nvim-lightbulb'";
    version = "56b9ce31ec9d09d560fe8787c0920f76bc208297";
    src = fetchFromGitHub {
      owner = "kosayoda";
      repo = "nvim-lightbulb";
      rev = "56b9ce31ec9d09d560fe8787c0920f76bc208297";
      fetchSubmodules = false;
      sha256 = "sha256-nw6H/dS4dHdrobnrfJVa8urWrMnbTWrA5bQJy9xbKXY=";
    };
    date = "2022-08-25";
  };
  "'plugin-nvim-lspconfig'" = {
    pname = "'plugin-nvim-lspconfig'";
    version = "8ebe6894dddaeb1459e1397c865f54fa5ecaac80";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "8ebe6894dddaeb1459e1397c865f54fa5ecaac80";
      fetchSubmodules = false;
      sha256 = "sha256-td813RwxxjyJTWEgy6JDcvm5R4RJxMKjP7qZPdfBgKM=";
    };
    date = "2023-01-15";
  };
  "'plugin-nvim-tetris'" = {
    pname = "'plugin-nvim-tetris'";
    version = "d17c99fb527ada98ffb0212ffc87ccda6fd4f7d9";
    src = fetchFromGitHub {
      owner = "alec-gibson";
      repo = "nvim-tetris";
      rev = "d17c99fb527ada98ffb0212ffc87ccda6fd4f7d9";
      fetchSubmodules = false;
      sha256 = "sha256-+69Fq5aMMzg9nV05rZxlLTFwQmDyN5/5HmuL2SGu9xQ=";
    };
    date = "2021-06-28";
  };
  "'plugin-nvim-tree.lua'" = {
    pname = "'plugin-nvim-tree.lua'";
    version = "1b13a49f913b58a5f1792ea81c13947a7988db8e";
    src = fetchFromGitHub {
      owner = "kyazdani42";
      repo = "nvim-tree.lua";
      rev = "1b13a49f913b58a5f1792ea81c13947a7988db8e";
      fetchSubmodules = false;
      sha256 = "sha256-iHB7/IbZ/JQu13+fSg9sMc/zTKr2Wa8l04Poets4ocE=";
    };
    date = "2023-01-16";
  };
  "'plugin-nvim-ts-autotag'" = {
    pname = "'plugin-nvim-ts-autotag'";
    version = "fdefe46c6807441460f11f11a167a2baf8e4534b";
    src = fetchFromGitHub {
      owner = "windwp";
      repo = "nvim-ts-autotag";
      rev = "fdefe46c6807441460f11f11a167a2baf8e4534b";
      fetchSubmodules = false;
      sha256 = "sha256-ltGiYNXWpWSI5RrWTVR+k6SZjcZbsHtH5m9uHTMKnzM=";
    };
    date = "2022-08-11";
  };
  "'plugin-nvim-ts-context-commentstring'" = {
    pname = "'plugin-nvim-ts-context-commentstring'";
    version = "a0f89563ba36b3bacd62cf967b46beb4c2c29e52";
    src = fetchFromGitHub {
      owner = "JoosepAlviste";
      repo = "nvim-ts-context-commentstring";
      rev = "a0f89563ba36b3bacd62cf967b46beb4c2c29e52";
      fetchSubmodules = false;
      sha256 = "sha256-HHsja6sz5+k4slmK697cRZZmkeCAt7Cjr0REYn15IX0=";
    };
    date = "2023-01-16";
  };
  "'plugin-nvim-unception'" = {
    pname = "'plugin-nvim-unception'";
    version = "fbf73e1ad089741b5ff146f902cc5ebcdf19b7b6";
    src = fetchFromGitHub {
      owner = "samjwill";
      repo = "nvim-unception";
      rev = "fbf73e1ad089741b5ff146f902cc5ebcdf19b7b6";
      fetchSubmodules = false;
      sha256 = "sha256-FWaBN9E+pwDrAQgH3R8fI8OkAaOr2WN/K8wW/hkxnAg=";
    };
    date = "2023-01-03";
  };
  "'plugin-nvim-web-devicons'" = {
    pname = "'plugin-nvim-web-devicons'";
    version = "6c38926351372ea87034dec26182b62c835ff3bc";
    src = fetchFromGitHub {
      owner = "kyazdani42";
      repo = "nvim-web-devicons";
      rev = "6c38926351372ea87034dec26182b62c835ff3bc";
      fetchSubmodules = false;
      sha256 = "sha256-CqrScj0h3uNb1awuYIRdTji2llyF61qdshQmmZT8d+M=";
    };
    date = "2023-01-10";
  };
  "'plugin-one-small-step-for-vimkind'" = {
    pname = "'plugin-one-small-step-for-vimkind'";
    version = "233c8940488d4072f9f8058798984cb68a49a319";
    src = fetchFromGitHub {
      owner = "jbyuki";
      repo = "one-small-step-for-vimkind";
      rev = "233c8940488d4072f9f8058798984cb68a49a319";
      fetchSubmodules = false;
      sha256 = "sha256-domOcZeTis5yjiksBRGIU7F4qyyde4NOpeiBCIehiCE=";
    };
    date = "2023-01-08";
  };
  "'plugin-playground'" = {
    pname = "'plugin-playground'";
    version = "01c27f37a1f067200680cacfb7b96f5ad2fa5cd6";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "playground";
      rev = "01c27f37a1f067200680cacfb7b96f5ad2fa5cd6";
      fetchSubmodules = false;
      sha256 = "sha256-dQJ44LbPVmTxL/pD7pQV3/tJxCwyovHGiC9yn1zhBY4=";
    };
    date = "2023-01-15";
  };
  "'plugin-plenary.nvim'" = {
    pname = "'plugin-plenary.nvim'";
    version = "1c7e3e6b0f4dd5a174fcea9fda8a4d7de593b826";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "1c7e3e6b0f4dd5a174fcea9fda8a4d7de593b826";
      fetchSubmodules = false;
      sha256 = "sha256-UWrp5ZoDRhOXSMsHZxrZHPfqBtgnKWf9SA8ChIVKF4o=";
    };
    date = "2023-01-10";
  };
  "'plugin-presence.nvim'" = {
    pname = "'plugin-presence.nvim'";
    version = "c1c54758824cbecd4e18065d37191f7666fdd097";
    src = fetchFromGitHub {
      owner = "andweeb";
      repo = "presence.nvim";
      rev = "c1c54758824cbecd4e18065d37191f7666fdd097";
      fetchSubmodules = false;
      sha256 = "sha256-v7/fN+NWsnR0APs23nX+kgeje9AlZ3aWy2H1JG57Q0g=";
    };
    date = "2022-11-16";
  };
  "'plugin-project.nvim'" = {
    pname = "'plugin-project.nvim'";
    version = "685bc8e3890d2feb07ccf919522c97f7d33b94e4";
    src = fetchFromGitHub {
      owner = "ahmedkhalf";
      repo = "project.nvim";
      rev = "685bc8e3890d2feb07ccf919522c97f7d33b94e4";
      fetchSubmodules = false;
      sha256 = "sha256-fW4ztvYpeXTC0DbkZS4usG/KENiMJG/sWVTD4e8k42g=";
    };
    date = "2022-10-29";
  };
  "'plugin-rust-tools.nvim'" = {
    pname = "'plugin-rust-tools.nvim'";
    version = "df584e84393ef255f5b8cbd709677d6a3a5bf42f";
    src = fetchFromGitHub {
      owner = "simrat39";
      repo = "rust-tools.nvim";
      rev = "df584e84393ef255f5b8cbd709677d6a3a5bf42f";
      fetchSubmodules = false;
      sha256 = "sha256-+/kK6MU2EiSBFbfqQJwLkJICXZpf8oiShbcvsls3V8A=";
    };
    date = "2023-01-07";
  };
  "'plugin-scope.nvim'" = {
    pname = "'plugin-scope.nvim'";
    version = "2db6d31de8e3a98d2b41c0f0d1f5dc299ee76875";
    src = fetchFromGitHub {
      owner = "tiagovla";
      repo = "scope.nvim";
      rev = "2db6d31de8e3a98d2b41c0f0d1f5dc299ee76875";
      fetchSubmodules = false;
      sha256 = "sha256-BdX+C5KBHZcFgDG2fXvhMl2Gp/6ffJWEBvA/JvVWh4I=";
    };
    date = "2022-06-26";
  };
  "'plugin-sort.nvim'" = {
    pname = "'plugin-sort.nvim'";
    version = "9e4065625317128f6a1c826f4a36f9b47600417a";
    src = fetchFromGitHub {
      owner = "sQVe";
      repo = "sort.nvim";
      rev = "9e4065625317128f6a1c826f4a36f9b47600417a";
      fetchSubmodules = false;
      sha256 = "sha256-1OhGO9lIZ2iTCgV1+bLZf7qZoo+ZDMKmjPHgBWYAmDE=";
    };
    date = "2022-07-08";
  };
  "'plugin-telescope.nvim'" = {
    pname = "'plugin-telescope.nvim'";
    version = "b69b33eded07341253bc1f0b4ae6bbc5c411a2ab";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope.nvim";
      rev = "b69b33eded07341253bc1f0b4ae6bbc5c411a2ab";
      fetchSubmodules = false;
      sha256 = "sha256-lkyqDrmruMfQdr7+GEpLS32Y1Zet0FfHSOriWsKSc4s=";
    };
    date = "2023-01-14";
  };
  "'plugin-trouble.nvim'" = {
    pname = "'plugin-trouble.nvim'";
    version = "83ec606e7065adf134d17f4af6bae510e3c491c1";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "trouble.nvim";
      rev = "83ec606e7065adf134d17f4af6bae510e3c491c1";
      fetchSubmodules = false;
      sha256 = "sha256-U9P5WgUsZjer2AekfrDeYDIpmcj0Hp4NEvX0Q5VqFlw=";
    };
    date = "2023-01-04";
  };
  "'plugin-twilight.nvim'" = {
    pname = "'plugin-twilight.nvim'";
    version = "8bb7fa7b918baab1ca81b977102ddb54afa63512";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "twilight.nvim";
      rev = "8bb7fa7b918baab1ca81b977102ddb54afa63512";
      fetchSubmodules = false;
      sha256 = "sha256-HqkdXI5nzSkdZeu56BY8Y0Yq64UFqnsxQmJVsBkRDS8=";
    };
    date = "2023-01-04";
  };
  "'plugin-vim-eunuch'" = {
    pname = "'plugin-vim-eunuch'";
    version = "291ef1f8c8996ca7715df1032a35a27b12d7b5cf";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-eunuch";
      rev = "291ef1f8c8996ca7715df1032a35a27b12d7b5cf";
      fetchSubmodules = false;
      sha256 = "sha256-t7D6vkEmhVDKdxqvHQ6811FENu/qM6MkrLl8lGADxDs=";
    };
    date = "2022-10-12";
  };
  "'plugin-vim-repeat'" = {
    pname = "'plugin-vim-repeat'";
    version = "24afe922e6a05891756ecf331f39a1f6743d3d5a";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-repeat";
      rev = "24afe922e6a05891756ecf331f39a1f6743d3d5a";
      fetchSubmodules = false;
      sha256 = "sha256-8rfZa3uKXB3TRCqaDHZ6DfzNbm7WaYnLvmTNzYtnKHg=";
    };
    date = "2021-01-24";
  };
  "'plugin-vim-surround'" = {
    pname = "'plugin-vim-surround'";
    version = "3d188ed2113431cf8dac77be61b842acb64433d9";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-surround";
      rev = "3d188ed2113431cf8dac77be61b842acb64433d9";
      fetchSubmodules = false;
      sha256 = "sha256-DZE5tkmnT+lAvx/RQHaDEgEJXRKsy56KJY919xiH1lE=";
    };
    date = "2022-10-25";
  };
  "'plugin-vimtex'" = {
    pname = "'plugin-vimtex'";
    version = "57da13348bce93dda80d4d4494db42e07c96b018";
    src = fetchFromGitHub {
      owner = "lervag";
      repo = "vimtex";
      rev = "57da13348bce93dda80d4d4494db42e07c96b018";
      fetchSubmodules = false;
      sha256 = "sha256-ZSIQY1mtO515osEvCs9IGjwIEiRNiYpjLck6WXLIX+g=";
    };
    date = "2023-01-15";
  };
  "'plugin-which-key.nvim'" = {
    pname = "'plugin-which-key.nvim'";
    version = "e4fa445065a2bb0bbc3cca85346b67817f28e83e";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "which-key.nvim";
      rev = "e4fa445065a2bb0bbc3cca85346b67817f28e83e";
      fetchSubmodules = false;
      sha256 = "sha256-fiufZp+NgowRlK3esTcPRc9Lbzbk8f6NX8n2H/DEQb4=";
    };
    date = "2023-01-12";
  };
  "'plugin-zen-mode.nvim'" = {
    pname = "'plugin-zen-mode.nvim'";
    version = "4313a5828e4d48c5f2f135f29d46f769a59dcfdc";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "zen-mode.nvim";
      rev = "4313a5828e4d48c5f2f135f29d46f769a59dcfdc";
      fetchSubmodules = false;
      sha256 = "sha256-lxOaiYXec0L3xuLhTuwXbcJ+/9mGBZKGB49XD9I1lhc=";
    };
    date = "2023-01-04";
  };
  "'plugin-zoxide.vim'" = {
    pname = "'plugin-zoxide.vim'";
    version = "7add42b0474b07c206c94d1693997e52d25c5fec";
    src = fetchFromGitHub {
      owner = "nanotee";
      repo = "zoxide.vim";
      rev = "7add42b0474b07c206c94d1693997e52d25c5fec";
      fetchSubmodules = false;
      sha256 = "sha256-GZZIBCQyfLLz7iBXhTH++LGSHz/NOgOB4svb5MgkWbM=";
    };
    date = "2022-06-29";
  };
  tree-sitter-norg = {
    pname = "tree-sitter-norg";
    version = "d7a466e182a532065a559dbfc7a847271d5e9c29";
    src = fetchFromGitHub {
      owner = "nvim-neorg";
      repo = "tree-sitter-norg";
      rev = "d7a466e182a532065a559dbfc7a847271d5e9c29";
      fetchSubmodules = false;
      sha256 = "sha256-kv3UiJUqMSF1qd3r4OCWomVTHTYjwX/EBRWm8mOSdwg=";
    };
    date = "2023-01-01";
  };
  tree-sitter-norg-meta = {
    pname = "tree-sitter-norg-meta";
    version = "8e1a9008eb9492e95eb9a65ab0ec0419cfa9c4c7";
    src = fetchFromGitHub {
      owner = "nvim-neorg";
      repo = "tree-sitter-norg-meta";
      rev = "8e1a9008eb9492e95eb9a65ab0ec0419cfa9c4c7";
      fetchSubmodules = false;
      sha256 = "sha256-1gOTQdqB/TpaJ2ClNY+/Gqsj7TkCgv9CNiX97oF8PGo=";
    };
    date = "2022-10-14";
  };
}
