# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  fast-syntax-highlighting = {
    pname = "fast-syntax-highlighting";
    version = "v1.55";
    src = fetchgit {
      url = "https://github.com/zdharma-continuum/fast-syntax-highlighting";
      rev = "v1.55";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0h7f27gz586xxw7cc0wyiv3bx0x3qih2wwh05ad85bh2h834ar8d";
    };
  };
  nix-shell = {
    pname = "nix-shell";
    version = "v0.5.0";
    src = fetchgit {
      url = "https://github.com/chisui/zsh-nix-shell";
      rev = "v0.5.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0za4aiwwrlawnia4f29msk822rj9bgcygw6a8a6iikiwzjjz0g91";
    };
  };
  zsh-autosuggestions = {
    pname = "zsh-autosuggestions";
    version = "v0.7.0";
    src = fetchgit {
      url = "https://github.com/zsh-users/zsh-autosuggestions";
      rev = "v0.7.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1g3pij5qn2j7v7jjac2a63lxd97mcsgw6xq6k5p7835q9fjiid98";
    };
  };
}
