# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
}: {
  airtame = {
    pname = "airtame";
    version = "4.5.2";
    src = fetchurl {
      url = "https://downloads.airtame.com/app/latest/linux/Airtame-4.5.2.deb";
      sha256 = "sha256-H4sVs8xEAduDjIngy92c+q149e6lCbzWXkFgA1GpMMU=";
    };
  };
  catch2 = {
    pname = "catch2";
    version = "v3.1.1";
    src = fetchFromGitHub {
      owner = "catchorg";
      repo = "Catch2";
      rev = "v3.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-l/bqW32c1vAzE3jN01VystZXuH2ZiOQGgXkh/Mcq2eI=";
    };
  };
  filen-desktop = {
    pname = "filen-desktop";
    version = "2.0.4";
    src = fetchurl {
      url = "https://cdn.filen.io/desktop/release/2.0.4/filen_x86_64.AppImage";
      sha256 = "sha256-WvMYMafUxaktJP0cSSkqIe2Hi6mkDH0PiFA9UVqzDM0=";
    };
  };
  lswt = {
    pname = "lswt";
    version = "ed1ae054d9af3c345f9f2c2003d179932c0c6b60";
    src = fetchgit {
      url = "https://git.sr.ht/~leon_plickat/lswt";
      rev = "ed1ae054d9af3c345f9f2c2003d179932c0c6b60";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Tiua9M2CJsYfmtmRXgR9ofmhwP8pRiYGbJdlBThWKMM=";
    };
  };
  picom = {
    pname = "picom";
    version = "c4107bb6cc17773fdc6c48bb2e475ef957513c7a";
    src = fetchFromGitHub {
      owner = "ibhagwan";
      repo = "picom";
      rev = "c4107bb6cc17773fdc6c48bb2e475ef957513c7a";
      fetchSubmodules = false;
      sha256 = "sha256-1hVFBGo4Ieke2T9PqMur1w4D0bz/L3FAvfujY9Zergw=";
    };
  };
  rescrobbled = {
    pname = "rescrobbled";
    version = "v0.6.1";
    src = fetchFromGitHub {
      owner = "InputUsername";
      repo = "rescrobbled";
      rev = "v0.6.1";
      fetchSubmodules = false;
      sha256 = "sha256-rAInYKXpOwmpwW5Q5tkQ6KTTi71/uOIdMRKP4zdanxM=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./rescrobbled-v0.6.1/Cargo.lock;
      outputHashes = {
      };
    };
  };
  river = {
    pname = "river";
    version = "8d43028277091687b853c59f20ced5d04dfc15dc";
    src = fetchFromGitHub {
      owner = "riverwm";
      repo = "river";
      rev = "8d43028277091687b853c59f20ced5d04dfc15dc";
      fetchSubmodules = true;
      sha256 = "sha256-8SjfQKlELSSmIHmOAAwkr8q8Ddx/kNcCLSHhVhcnuaY=";
    };
  };
  waybar = {
    pname = "waybar";
    version = "1374b0fce40f283b113e051f0558564fa1d9ad22";
    src = fetchFromGitHub {
      owner = "Alexays";
      repo = "waybar";
      rev = "1374b0fce40f283b113e051f0558564fa1d9ad22";
      fetchSubmodules = false;
      sha256 = "sha256-UG233AXx7xU9O3/hs5mIXun7PCYibJvlDL1tQhB5gxE=";
    };
  };
  waybar-mpris = {
    pname = "waybar-mpris";
    version = "1233aa9f90d75ec2bbd82afde757309fd9abab3a";
    src = fetchFromGitHub {
      owner = "b10n";
      repo = "waybar-mpris";
      rev = "1233aa9f90d75ec2bbd82afde757309fd9abab3a";
      fetchSubmodules = false;
      sha256 = "sha256-CV8hNW/KMFKfxe126ENV5h6qhypU9bz3u3DnTFa/94I=";
    };
  };
  waylock = {
    pname = "waylock";
    version = "v0.4.2";
    src = fetchFromGitHub {
      owner = "ifreund";
      repo = "waylock";
      rev = "v0.4.2";
      fetchSubmodules = true;
      sha256 = "sha256-yWjWcnGa4a+Dpc82H65yr8H7v88g/tDq0FSguubhbEI=";
    };
  };
  wlroots = {
    pname = "wlroots";
    version = "96ebf7426096f4d4ca08934377195def706c8243";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/ifreund/wlroots";
      rev = "96ebf7426096f4d4ca08934377195def706c8243";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-cDt45vkgl1cq5avyMuZ94zdWyWmKWtUQ6/VzuSpP4y4=";
    };
  };
  wob = {
    pname = "wob";
    version = "dcf9bcf73cdc5204c6fc2a08f60ed64ebac38980";
    src = fetchFromGitHub {
      owner = "francma";
      repo = "wob";
      rev = "dcf9bcf73cdc5204c6fc2a08f60ed64ebac38980";
      fetchSubmodules = false;
      sha256 = "sha256-3O2RdoL8FjOgO2SZG5j1S8Qq82CN3owCLkqCk/0w2ks=";
    };
  };
}
