# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  git-aliases = {
    pname = "git-aliases";
    version = "7653169af41a9fa93d6f5c5e2aedb4c7ce801840";
    src = fetchFromGitHub {
      owner = "GitAlias";
      repo = "gitalias";
      rev = "7653169af41a9fa93d6f5c5e2aedb4c7ce801840";
      fetchSubmodules = false;
      sha256 = "sha256-nLXqRA6iB2ng/ESeu4dmccTNMg4wYPvBYJ2MlY1ci/A=";
    };
    date = "2026-08-06";
  };
}
