# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  git-aliases = {
    pname = "git-aliases";
    version = "1e46c48e5ca019d60112c5b8449d4feceb305b55";
    src = fetchFromGitHub {
      owner = "GitAlias";
      repo = "gitalias";
      rev = "1e46c48e5ca019d60112c5b8449d4feceb305b55";
      fetchSubmodules = false;
      sha256 = "sha256-WVqK/qLUu+LlQ6Fehtnz4s5ttmPJm3ce3pN14n3dkoU=";
    };
    date = "2026-05-23";
  };
}
